/** Build scripts/_eu-es-eu-ovr.json — Spanish lemma → [eu, aux] */
import fs from "fs";

const taken = new Set(
  JSON.parse(fs.readFileSync("scripts/_eu-src-verbs.json", "utf8")).taken.map((t) =>
    t.replace(/^v:/, "").toLowerCase(),
  ),
);

/** Preferred dictionary forms. Entries whose EU is in `taken` cause row skip. */
const OVR = {
  // —— taken (skip) ——
  ser: ["izan", "nor"],
  estar: ["egon", "nor"],
  tener: ["eduki", "nork"],
  hacer: ["egin", "nork"],
  ir: ["joan", "nor"],
  decir: ["esan", "nork"],
  querer: ["nahi izan", "nork"],
  saber: ["jakin", "nork"],
  ver: ["ikusi", "nork"],
  venir: ["etorri", "nor"],
  tomar: ["hartu", "nork"],
  encontrar: ["aurkitu", "nork"],
  dar: ["eman", "nork"],
  poner: ["jarri", "nork"],
  pedir: ["eskatu", "nork"],
  quedarse: ["geratu", "nor"],
  oír: ["entzun", "nork"],
  dejar: ["utzi", "nork"],
  llegar: ["iritsi", "nor"],
  creer: ["sinetsi", "nork"],
  conocer: ["ezagutu", "nork"],
  salir: ["atera", "nor"],
  vivir: ["bizi izan", "nor"],
  escribir: ["idatzi", "nork"],
  abrir: ["ireki", "nork"],
  leer: ["irakurri", "nork"],
  terminar: ["amaitu", "nork"],
  entender: ["ulertu", "nork"],
  jugar: ["jolastu", "nor"],
  comer: ["jan", "nork"],
  beber: ["edan", "nork"],
  dormir: ["lo egin", "nork"],
  esperar: ["itxaron", "nork"],
  trabajar: ["lan egin", "nork"],
  pensar: ["pentsatu", "nork"],
  mostrar: ["erakutsi", "nork"],
  llevar: ["eraman", "nork"],
  comenzar: ["hasi", "nor"],
  llamar: ["deitu", "nork"],
  seguir: ["jarraitu", "nork"],
  perder: ["galdu", "nork"],
  mirar: ["begiratu", "nork"],
  recibir: ["jaso", "nork"],
  devolver: ["itzuli", "nork"],
  responder: ["erantzun", "nork"],
  permitir: ["baimendu", "nork"],
  ofrecer: ["eskaini", "nork"],
  aprender: ["ikasi", "nork"],
  olvidar: ["ahaztu", "nori"],
  explicar: ["azaldu", "nork"],
  decidir: ["erabaki", "nork"],
  intentar: ["saiatu", "nor"],
  usar: ["erabili", "nork"],
  ayudar: ["lagundu", "nork"],
  cambiar: ["aldatu", "nork"],
  continuar: ["jarraitu", "nork"],
  parar: ["gelditu", "nor"],
  ganar: ["irabazi", "nork"],
  vender: ["saldu", "nork"],
  comprar: ["erosi", "nork"],
  pagar: ["ordaindu", "nork"],
  buscar: ["bilatu", "nork"],
  estudiar: ["ikasi", "nork"],
  lograr: ["lortu", "nork"],
  servir: ["zerbitzatu", "nork"],
  correr: ["korrika egin", "nork"],
  reír: ["barre egin", "nork"],
  descubrir: ["aurkitu", "nork"],
  nacer: ["jaio", "nor"],
  morir: ["hil", "nor"],
  caer: ["erori", "nor"],
  entrar: ["sartu", "nor"],
  subir: ["igo", "nor"],
  bajar: ["jaitsi", "nor"],
  volver: ["itzuli", "nor"],
  "hacer falta": ["behar izan", "nork"],
  gustar: ["gustatu", "nori"],
  reconocer: ["aitortu", "nork"],
  golpear: ["jo", "nork"],
  prometer: ["agindu", "nork"],
  conducir: ["gidatu", "nork"],
  cubrir: ["estali", "nork"],
  mantener: ["mantendu", "nork"],
  sufrir: ["jasan", "nork"],
  perseguir: ["jarraitu", "nork"],
  pintar: ["margotu", "nork"],
  apagar: ["itzali", "nork"],
  unir: ["elkartu", "nork"],
  resolver: ["ebatzi", "nork"],
  defender: ["defendatu", "nork"],
  elegir: ["hautatu", "nork"],
  agarrar: ["heldu", "nork"],
  llenar: ["bete", "nork"],
  castigar: ["zigortu", "nork"],
  reunir: ["elkartu", "nork"],
  cumplir: ["bete", "nork"],
  escuchar: ["entzun", "nork"],
  levantar: ["altxatu", "nork"],
  disculpar: ["barkatu", "nork"],
  enviar: ["bidali", "nork"],
  guardar: ["gorde", "nork"],
  empujar: ["bultzatu", "nork"],
  recordar: ["gogoratu", "nork"],
  tocar: ["ukitu", "nork"],
  contar: ["kontatu", "nork"],
  gritar: ["oihukatu", "nork"],
  cerrar: ["itxi", "nork"],
  traer: ["ekarri", "nork"],
  esconder: ["ezkutatu", "nork"],
  acercar: ["hurbildu", "nor"],
  llorar: ["negar egin", "nork"],
  despertar: ["esnatu", "nor"],
  preparar: ["prestatu", "nork"],
  quitar: ["kendu", "nork"],
  soltar: ["askatu", "nork"],
  cantar: ["abestu", "nork"],
  presentar: ["aurkeztu", "nork"],
  aceptar: ["onartu", "nork"],
  romper: ["apurtu", "nork"],
  cortar: ["moztu", "nork"],
  rechazar: ["baztertu", "nork"],
  perdonar: ["barkatu", "nork"],
  bailar: ["dantzatu", "nork"],
  alejar: ["urrundu", "nor"],
  proteger: ["babestu", "nork"],
  soñar: ["amestu", "nork"],
  proponer: ["proposatu", "nork"],
  invitar: ["gonbidatu", "nork"],
  encender: ["piztu", "nork"],
  arreglar: ["konpondu", "nork"],
  agradecer: ["eskertu", "nork"],
  alzar: ["altxatu", "nork"],
  mezclar: ["nahastu", "nork"],
  separar: ["banandu", "nork"],
  pegar: ["itsatsi", "nork"],
  firmar: ["sinatu", "nork"],
  crear: ["sortu", "nork"],
  repartir: ["banatu", "nork"],
  autorizar: ["baimendu", "nork"],
  ordenar: ["ordenatu", "nork"],
  anular: ["ezeztatu", "nork"],
  costar: ["kostatu", "nori"],
  desmentir: ["ukatu", "nork"],
  coser: ["josi", "nork"],
  vestir: ["jantzi", "nork"],
  desvestir: ["erantzi", "nork"],
  denunciar: ["salatu", "nork"],
  alargar: ["luzatu", "nork"],
  justificar: ["justifikatu", "nork"],
  limitar: ["mugatu", "nork"],
  afirmar: ["baieztatu", "nork"],
  confirmar: ["berretsi", "nork"],
  examinar: ["aztertu", "nork"],
  juzgar: ["epaitu", "nork"],
  saludar: ["agurtu", "nork"],
  acusar: ["akusatu", "nork"],
  exigir: ["eskatu", "nork"],
  debatir: ["eztabaidatu", "nork"],
  aclarar: ["argitu", "nork"],
  impugnar: ["aurkaratu", "nork"],
  relativizar: ["erlatibizatu", "nork"],
  "poner en perspectiva": ["erlatibizatu", "nork"],
  cometer: ["egin", "nork"],
  "oír en comparecencia": ["entzun", "nork"],
  instruir: ["irakatsi", "nork"],
  ratificar: ["berretsi", "nork"],
  alterar: ["aldatu", "nork"],
  "poner en común": ["partekatu", "nork"],
  remediar: ["konpondu", "nork"],
  requerir: ["eskatu", "nork"],
  incluir: ["sartu", "nork"],
  callarse: ["isildu", "nor"],
  dormirse: ["lokartu", "nor"],
  acordarse: ["gogoratu", "nork"],
  "resultar ser": ["izan", "nor"],
  celebrarse: ["egin", "nor"],
  pretender: ["nahi izan", "nork"],
  acompañar: ["lagundu", "nork"],
  llevarse: ["eraman", "nork"],
  depositar: ["utzi", "nork"],
  encomendar: ["agindu", "nork"],
  clausurar: ["itxi", "nork"],
  extraer: ["atera", "nork"],
  otorgar: ["eman", "nork"],
  remitir: ["bidali", "nork"],
  despachar: ["bidali", "nork"],
  acarrear: ["ekarri", "nork"],
  burlarse: ["barre egin", "nork"],
  mofarse: ["barre egin", "nork"],
  ataviar: ["jantzi", "nork"],
  "abogar por": ["alde egin", "nork"],
  refrendar: ["berretsi", "nork"],
  extirpar: ["kendu", "nork"],
  desenredar: ["askatu", "nork"],
  halagar: ["goraipatu", "nork"],
  blandir: ["erakutsi", "nork"],
  atajar: ["gelditu", "nork"],
  ultimar: ["amaitu", "nork"],
  recortar: ["moztu", "nork"],
  enganchar: ["lotu", "nork"],
  incensar: ["goraipatu", "nork"],
  espolear: ["bultzatu", "nork"],
  escudriñar: ["aztertu", "nork"],
  redimir: ["salbatu", "nork"],
  refutar: ["ezeztatu", "nork"],
  fallecer: ["hil", "nor"],
  inquirir: ["galdetu", "nork"],
  apartarse: ["urrundu", "nor"],
  inmiscuirse: ["sartu", "nor"],
  zurrar: ["jo", "nork"],
  suscitar: ["piztu", "nork"],
  acentuar: ["nabarmendu", "nork"],
  deslindar: ["mugatu", "nork"],
  amparar: ["babestu", "nork"],
  preceptuar: ["agindu", "nork"],
  circunscribir: ["mugatu", "nork"],
  aflojar: ["askatu", "nork"],
  ensanchar: ["zabaldu", "nork"],
  acortar: ["laburtu", "nork"],
  "poner en claro": ["argitu", "nork"],
  enturbiar: ["nahastu", "nork"],
  desatar: ["askatu", "nork"],
  anudar: ["lotu", "nork"],
  zanjar: ["ebatzi", "nork"],
  dirimir: ["ebatzi", "nork"],
  acceder: ["sartu", "nor"],
  conceder: ["eman", "nork"],
  ceder: ["utzi", "nork"],
  enmendar: ["zuzendu", "nork"],
  aprobar: ["onartu", "nork"],
  captar: ["hartu", "nork"],
  tutelar: ["zaindu", "nork"],
  tabicar: ["bereizi", "nork"],
  compensar: ["ordaindu", "nork"],
  concertar: ["adostu", "nork"],
  convocar: ["deitu", "nork"],
  corroborar: ["berretsi", "nork"],
  abonar: ["ordaindu", "nork"],
  decretar: ["agindu", "nork"],
  despejar: ["garbitu", "nork"],
  desposeer: ["kendu", "nork"],
  despojar: ["kendu", "nork"],
  desvincular: ["askatu", "nork"],
  desolidarizar: ["banandu", "nork"],
  disociar: ["bereizi", "nork"],
  apartar: ["baztertu", "nork"],
  extraviar: ["galdu", "nork"],
  "incurrir en": ["erori", "nor"],
  abarcar: ["hartu", "nork"],
  emprender: ["hasi", "nor"],
  esforzarse: ["saiatu", "nor"],
  desempeñar: ["bete", "nork"],
  atascarse: ["gelditu", "nor"],
  enredarse: ["nahastu", "nor"],
  destinar: ["zuzendu", "nork"],
  avivar: ["piztu", "nork"],
  detraer: ["kendu", "nork"],
  desglosar: ["xehatu", "nork"],
  remunerar: ["ordaindu", "nork"],
  marginar: ["baztertu", "nork"],
  mellar: ["kaltetu", "nork"],
  deteriorar: ["hondatu", "nork"],
  enderezar: ["zuzendu", "nork"],
  provisionar: ["hornitu", "nork"],
  reembolsar: ["itzuli", "nork"],
  invocar: ["deitu", "nork"],
  sustituirse: ["ordezkatu", "nor"],
  desmarcarse: ["bereizi", "nor"],
  extenderse: ["zabaldu", "nor"],
  desplegar: ["zabaldu", "nork"],
  tender: ["zabaldu", "nork"],
  extender: ["zabaldu", "nork"],

  // —— new dictionary forms ——
  poder: ["ahal izan", "nork"],
  deber: ["zor izan", "nork"],
  amar: ["maite izan", "nork"],
  convertirse: ["bilakatu", "nor"],
  irse: ["alde egin", "nork"],
  hablar: ["mintzatu", "nork"],
  pasar: ["igaro", "nor"],
  sostener: ["eutsi", "nork"],
  parecer: ["iruditu", "nori"],
  sentir: ["sentitu", "nork"],
  habitar: ["bizileku izan", "nor"],
  obtener: ["eskuratu", "nork"],
  "volver a casa": ["etxera itzuli", "nor"],
  regresar: ["itzulera egin", "nor"],
  valer: ["balio izan", "nor"],
  bastar: ["nahikoa izan", "nor"],
  vislumbrar: ["antzeman", "nork"],
  sonreír: ["irribarre egin", "nork"],
  retomar: ["berriro hartu", "nork"],
  mentir: ["gezurra esan", "nork"],
  desaparecer: ["desagertu", "nor"],
  "volver a ver": ["berriro ikusi", "nork"],
  retener: ["atxiki", "nork"],
  "reunirse con": ["elkarrekin bildu", "nork"],
  avisar: ["ohartarazi", "nork"],
  alcanzar: ["helburu lortu", "nork"],
  destruir: ["suntsitu", "nork"],
  temer: ["beldur izan", "nork"],
  sorprender: ["harritu", "nork"],
  pertenecer: ["dagokiona izan", "nor"],
  construir: ["eraiki", "nork"],
  producir: ["produzitu", "nork"],
  traducir: ["itzulpena egin", "nork"],
  introducir: ["sarrarazi", "nork"],
  cocer: ["egosi", "nork"],
  compadecer: ["erruki izan", "nork"],
  concluir: ["ondorioztatu", "nork"],
  interrumpir: ["eten", "nork"],
  decepcionar: ["huts egin", "nork"],
  concebir: ["asmatu", "nork"],
  llover: ["euria egin", "nork"],
  "volver a partir": ["berriro abiatu", "nor"],
  actuar: ["jardun", "nork"],
  reflexionar: ["hausnartu", "nork"],
  crecer: ["haztu", "nor"],
  engordar: ["koipetu", "nor"],
  adelgazar: ["argaldu", "nor"],
  obedecer: ["obeditu", "nork"],
  desobedecer: ["desobeditu", "nork"],
  establecer: ["ezarri", "nork"],
  traicionar: ["traizio egin", "nork"],
  alimentar: ["elikatu", "nork"],
  garantizar: ["bermatu", "nork"],
  advertir: ["abisu eman", "nork"],
  aplaudir: ["txalotu", "nork"],
  sonrojarse: ["gorritu", "nor"],
  envejecer: ["zahartu", "nor"],
  ralentizar: ["moteldu", "nork"],
  invertir: ["inbertitu", "nork"],
  definir: ["definitu", "nork"],
  suministrar: ["hornitu", "nork"],
  tirar: ["bota", "nork"],
  reencontrar: ["berriro aurkitu", "nork"],
  colocar: ["kokatu", "nork"],
  girar: ["biratu", "nork"],
  ocupar: ["okupatu", "nork"],
  caminar: ["ibilaldi egin", "nork"],
  rezar: ["otoitz egin", "nork"],
  importar: ["axola izan", "nori"],
  faltar: ["faltatu", "nori"],
  salvar: ["salbatu", "nork"],
  imaginar: ["imajinatu", "nork"],
  volar: ["hegaldu", "nor"],
  resbalar: ["irristatu", "nor"],
  añadir: ["gehitu", "nork"],
  moverse: ["mugitu", "nor"],
  apretar: ["estutu", "nork"],
  cruzar: ["zeharkatu", "nork"],
  repetir: ["errepikatu", "nork"],
  acostar: ["etzan", "nor"],
  avanzar: ["aurreratu", "nor"],
  adorar: ["gurtu", "nork"],
  preferir: ["hobetsi", "nork"],
  cesar: ["utzarazi", "nork"],
  "traer de vuelta": ["berriro ekarri", "nork"],
  impedir: ["eragotzi", "nork"],
  calmar: ["lasaitu", "nork"],
  lanzar: ["jaurti", "nork"],
  rodar: ["biraka ibili", "nor"],
  instalar: ["instalatu", "nork"],
  parecerse: ["antza izan", "nor"],
  ignorar: ["ezjakinarazi", "nork"],
  inclinar: ["makurtu", "nork"],
  atreverse: ["ausartu", "nor"],
  engañar: ["engainatu", "nork"],
  jurar: ["zin egin", "nork"],
  existir: ["existitu", "nor"],
  notar: ["ohartu", "nor"],
  divertir: ["dibertitu", "nork"],
  fijar: ["finkatu", "nork"],
  interesar: ["interesatu", "nori"],
  besar: ["musukatu", "nork"],
  saltar: ["jauzi egin", "nork"],
  anunciar: ["iragarri", "nork"],
  escapar: ["ihes egin", "nork"],
  abandonar: ["abandonatu", "nork"],
  molestar: ["molestatu", "nork"],
  asegurar: ["segurtatu", "nork"],
  apoyar: ["sostengatu", "nork"],
  detestar: ["gorroto izan", "nork"],
  arrastrar: ["arrastatu", "nork"],
  cargar: ["kargatu", "nork"],
  fluir: ["isuri", "nor"],
  suponer: ["suposatu", "nork"],
  "casarse con": ["ezkondu", "nor"],
  asombrar: ["txunditu", "nork"],
  sacudir: ["astindu", "nork"],
  observar: ["behatu", "nork"],
  arrancar: ["erauzi", "nork"],
  atrapar: ["harrapatu", "nork"],
  adivinar: ["asmatze egin", "nork"],
  rodear: ["inguratu", "nork"],
  comprobar: ["egiaztatu", "nork"],
  evitar: ["saihestu", "nork"],
  quemar: ["erre", "nork"],
  formar: ["eratu", "nork"],
  obligar: ["behartu", "nork"],
  tratar: ["tratatu", "nork"],
  criar: ["hazkuntza egin", "nork"],
  herir: ["zauritu", "nork"],
  respirar: ["arnastu", "nork"],
  durar: ["iraun", "nor"],
  marcar: ["markatu", "nork"],
  entrenar: ["entrenatu", "nork"],
  arriesgar: ["arriskatu", "nork"],
  colgar: ["zintzilikatu", "nork"],
  atacar: ["eraso", "nork"],
  fumar: ["erretze egin", "nork"],
  retirar: ["erretiratu", "nork"],
  entregar: ["entregatu", "nork"],
  "hacer llegar": ["iritsiarazi", "nork"],
  reencaminar: ["berbideratu", "nork"],
  contabilizar: ["kontabilizatu", "nork"],
  auditar: ["auditatu", "nork"],
  certificar: ["ziurtatu", "nork"],
  validar: ["balioztatu", "nork"],
  invalidar: ["baliogabetu", "nork"],
  desautorizar: ["desbaimendu", "nork"],
  inhabilitar: ["desgaitu", "nork"],
  delegar: ["delegatu", "nork"],
  subcontratar: ["azpikontratatu", "nork"],
  externalizar: ["kanporatu", "nork"],
  internalizar: ["barneratu", "nork"],
  centralizar: ["zentralizatu", "nork"],
  descentralizar: ["deszentralizatu", "nork"],
  federar: ["federatu", "nork"],
  orquestar: ["orkestatu", "nork"],
  dirigir: ["zuzendaritza egin", "nork"],
  supervisar: ["gainbegiratu", "nork"],
  monitorizar: ["monitorizatu", "nork"],
  parametrizar: ["parametrizatu", "nork"],
  configurar: ["konfiguratu", "nork"],
  reconfigurar: ["berkonfiguratu", "nork"],
  "guardar copia": ["babeskopia egin", "nork"],
  restaurar: ["berrezarri", "nork"],
  archivar: ["artxibatu", "nork"],
  desarchivar: ["desartxibatu", "nork"],
  comprimir: ["konprimitu", "nork"],
  descomprimir: ["deskonprimitu", "nork"],
  cifrar: ["zifratu", "nork"],
  descifrar: ["deszifratu", "nork"],
  encriptar: ["enkriptatu", "nork"],
  tokenizar: ["tokenizatu", "nork"],
  anonimizar: ["anonimizatu", "nork"],
  seudonimizar: ["pseudonimizatu", "nork"],
  indexar: ["indexatu", "nork"],
  reindexar: ["berindexatu", "nork"],
  consultar: ["kontsultatu", "nork"],
  paginar: ["orrikatu", "nork"],
  filtrar: ["iragazi", "nork"],
  agrupar: ["taldekatu", "nork"],
  agregar: ["gehitu", "nork"],
  desagregar: ["desagregatu", "nork"],
  normalizar: ["normalizatu", "nork"],
  desnormalizar: ["desnormalizatu", "nork"],
  estandarizar: ["estandarizatu", "nork"],
  industrializar: ["industrializatu", "nork"],
  automatizar: ["automatizatu", "nork"],
  robotizar: ["robotizatu", "nork"],
  digitalizar: ["digitalizatu", "nork"],
  escanear: ["eskaneatu", "nork"],
  imprimir: ["inprimatu", "nork"],
  reimprimir: ["berrinprimatu", "nork"],
  "enviar por fax": ["faxez bidali", "nork"],
  notificar: ["jakinarazi", "nork"],
  escalar: ["eskalatu", "nork"],
  desescalar: ["deseskalatu", "nork"],
  "quitar prioridad": ["lehentasuna kendu", "nork"],
  planificar: ["planifikatu", "nork"],
  replanificar: ["berplanifikatu", "nork"],
  "fijar plazos": ["epeak ezarri", "nork"],
  cartografiar: ["kartografiatu", "nork"],
  modelar: ["modelizatu", "nork"],
  "hacer prototipo": ["prototipatu", "nork"],
  iterar: ["iteratu", "nork"],
  refinar: ["finkapen egin", "nork"],
  optimizar: ["optimizatu", "nork"],
  maximizar: ["maximizatu", "nork"],
  estabilizar: ["egonkortu", "nork"],
  desestabilizar: ["desegonkortu", "nork"],
  "quitar seguridad": ["segurtasuna kendu", "nork"],
  bloquear: ["blokeatu", "nork"],
  desbloquear: ["desblokeatu", "nork"],
  blindar: ["blindatu", "nork"],
  segmentar: ["segmentatu", "nork"],
  trocear: ["zatikatu", "nork"],
  fraccionar: ["zatikatze egin", "nork"],
  fusionar: ["bateratu", "nork"],
  escindir: ["bitan banatu", "nork"],
  conciliar: ["adiskidetu", "nork"],
  convenir: ["komeni izan", "nori"],
  prever: ["aurreikusi", "nork"],
  falsificar: ["faltsutu", "nork"],
  satisfacer: ["asetu", "nork"],
  sobrevalorar: ["gehiegi baloratu", "nork"],
  rehacer: ["berregin", "nork"],
  "obrar mal": ["gaizki jokatu", "nork"],
  espesar: ["loditu", "nork"],
  endurecer: ["gogortu", "nork"],
  ablandar: ["bigundu", "nork"],
  reafirmar: ["berrespena eman", "nork"],
  capitalizar: ["kapitalizatu", "nork"],
  "incluir en presupuesto": ["aurrekontuan sartu", "nork"],
  transferir: ["transferitu", "nork"],
  recobrar: ["berreskuratu", "nork"],
  "cubrir de nuevo": ["berrestali", "nork"],
  liquidar: ["likidatu", "nork"],
  saldar: ["kitatu", "nork"],
  "liquidar saldo": ["saldoa kitatu", "nork"],
  reasignar: ["berrizendatu", "nork"],
  "reasignar presupuesto": ["aurrekontua berrizendatu", "nork"],
  rearmar: ["berrarmatu", "nork"],
  equilibrar: ["oreka jarri", "nork"],
  contrapartidar: ["kontrapartida egin", "nork"],
  rectificar: ["zuzenketa egin", "nork"],
  corregir: ["zuzendu", "nork"],
  revisar: ["berrikusi", "nork"],
  reexaminar: ["berraztertu", "nork"],
  reevaluar: ["berrebaluatu", "nork"],
  "estar a punto de": ["zorian egon", "nor"],
  acontecer: ["gertatu", "nor"],
  sobrevenir: ["gertaera izan", "nor"],
  intervenir: ["esku hartu", "nork"],
  provenir: ["etortzeari ekin", "nor"],
  vencer: ["garaitu", "nork"],
  decaer: ["gainbehera egin", "nork"],
  cercar: ["inguratze egin", "nork"],
  eclosionar: ["eclosionatu", "nor"],
  precluir: ["eragotze egin", "nork"],
  absolver: ["absolbitu", "nork"],
  disolver: ["desegin", "nork"],
  conmover: ["hunkitu", "nork"],
  mover: ["mugimendu egin", "nork"],
  ascender: ["igoera egin", "nor"],
  proveer: ["hornikuntza eman", "nork"],
  desproveer: ["deshornitu", "nork"],
  intimar: ["intimatu", "nork"],
  fingir: ["itxurak egin", "nork"],
  gimotear: ["negarrez egin", "nork"],
  ceñir: ["gerriko jarri", "nork"],
  estrechar: ["estutze egin", "nork"],
  ungir: ["ungi egin", "nork"],
  asomar: ["agerpen egin", "nor"],
  desunir: ["banantze egin", "nork"],
  constreñir: ["derrigortu", "nork"],
  forzar: ["behartze egin", "nork"],
  cercenar: ["ebaki", "nork"],
  quebrantar: ["hautsi", "nork"],
  matar: ["hiltze egin", "nork"],
  diferir: ["atzeratu", "nork"],
  sentar: ["eseri", "nor"],
  susurrar: ["xuxurlatu", "nork"],
  freír: ["frijitu", "nork"],
  lucir: ["distiratu", "nor"],
  relucir: ["distiratze egin", "nor"],
  dañar: ["kaltetu", "nork"],
  murmurar: ["murmuratu", "nork"],
  maldecir: ["madarikatu", "nork"],
  vedar: ["debekatze egin", "nork"],
  vaticinar: ["iragarpen egin", "nork"],
  releer: ["berrirakurri", "nork"],
  desdecirse: ["atzera egin", "nork"],
  describir: ["deskribatu", "nork"],
  sustraer: ["ken", "nork"],
  distraer: ["distraitu", "nork"],
  abstraer: ["abstraitu", "nork"],
  hendir: ["pitzatu", "nork"],
  hender: ["pitzatze egin", "nork"],
  morder: ["kosk egin", "nork"],
  torcer: ["bihurritu", "nork"],
  moler: ["eho", "nork"],
  recoser: ["berrjosi", "nork"],
  descoser: ["desjosi", "nork"],
  convencer: ["konbentzitu", "nork"],
  quebrar: ["hauste egin", "nork"],
  corromper: ["usteldu", "nork"],
  emitir: ["igorri", "nork"],
  omitir: ["ahazte egin", "nork"],
  someter: ["menperatu", "nork"],
  transmitir: ["transmititu", "nork"],
  destituir: ["kargugabetu", "nork"],
  revestir: ["estaltze egin", "nork"],
  sojuzgar: ["menperatze egin", "nork"],
  "dar mal servicio": ["gaizki zerbitzatu", "nork"],
  presentir: ["aurresan", "nork"],
  consentir: ["onespena eman", "nork"],
  armonizar: ["harmonizatu", "nork"],
  desestimar: ["baztertze egin", "nork"],
  alegar: ["alega egin", "nork"],
  "firmar al margen": ["bazterrean sinatu", "nork"],
  dictar: ["diktatu", "nork"],
  divulgar: ["zabalddu", "nork"],
  barruntar: ["susmatu", "nork"],
  tardarse: ["luzatze egin", "nor"],
  "guisar a fuego lento": ["astiro egosi", "nork"],
  abuchear: ["txistu egin", "nork"],
  "mofarse de": ["barregarri utzi", "nork"],
  escarnecer: ["mespretxatu", "nork"],
  mendigar: ["eske egin", "nork"],
  chochear: ["txoratu", "nor"],
  reconvenir: ["errieta egin", "nork"],
  "tratar con aspereza": ["gogor tratatu", "nork"],
  sobornar: ["eroskeria egin", "nork"],
  pignorar: ["bahitu", "nork"],
  denostar: ["iraindu", "nork"],
  "andarse con rodeos": ["inguruka ibili", "nor"],
  amasar: ["oreatu", "nork"],
  "cargar con dureza": ["gogor jo", "nork"],
  zozobrar: ["hondoratu", "nor"],
  ultrajar: ["iraintze egin", "nork"],
  "dar rodeos": ["inguruka aritu", "nor"],
  arengar: ["arenga egin", "nork"],
  fustigar: ["gogor kritikatu", "nork"],
  estipular: ["ezarpen egin", "nork"],
  transigir: ["amore eman", "nork"],
  usurpar: ["usurpatu", "nork"],
  sucumbir: ["erorketa egin", "nor"],
  suplicar: ["erregutu", "nork"],
  recriminar: ["leporatu", "nork"],
  promulgar: ["aldarrikatu", "nork"],
  prorrogar: ["luzapen egin", "nork"],
  estorbar: ["oztopatu", "nork"],
  erigir: ["eraikuntza egin", "nork"],
  escamotear: ["lapurtu", "nork"],
  exculpar: ["errugabetu", "nork"],
  disuadir: ["galarazi", "nork"],
  eludir: ["saihestze egin", "nork"],
  emanar: ["ateratu", "nor"],
  derogar: ["indargabetu", "nork"],
  desheredar: ["ondorengotasuna kendu", "nork"],
  deplorar: ["deitoratu", "nork"],
  desdeñar: ["mespretxu egin", "nork"],
  balbucir: ["motelduta mintzatu", "nork"],
  tartamudear: ["zurritu", "nork"],
  jalonar: ["mugarritu", "nork"],
  lesionar: ["zauritze egin", "nork"],
  "condenar al ostracismo": ["ostrazismora kondenatu", "nork"],
  palidecer: ["zuriak atera", "nor"],
  perjurar: ["zin hautsi", "nork"],
  peregrinar: ["erromes joan", "nor"],
  piafar: ["piafatu", "nor"],
  pisotear: ["zapaldu", "nork"],
  pontificar: ["doktrina eman", "nork"],
  pulverizar: ["hauts egin", "nork"],
  raciocinar: ["arrazoitu", "nork"],
  regentear: ["zuzendaritza hartu", "nork"],
  requisitar: ["bahitze egin", "nork"],
  saquear: ["arpilatu", "nork"],
  minar: ["ahuldu", "nork"],
  sellar: ["zigilatu", "nork"],
  contener: ["eustea egin", "nork"],
  "picar la curiosidad": ["jakin-mina piztu", "nork"],
  acechar: ["zaintze egin", "nork"],
  agotar: ["agortu", "nork"],
  hechizar: ["liluratu", "nork"],
  mancillar: ["zikindu", "nork"],
  imputar: ["leporatze egin", "nork"],
  inferir: ["ondorioztu", "nork"],
  inhumar: ["ehortzi", "nork"],
  injuriar: ["irain egin", "nork"],
  interpelar: ["galdegin", "nork"],
  implorar: ["erregu egin", "nork"],
  despreciar: ["gutxietsi", "nork"],
  menospreciar: ["gutxieste egin", "nork"],
  merodear: ["ibilte egin", "nor"],
  macerar: ["beratzen utzi", "nork"],
  obliterar: ["ezabatu", "nork"],
  prevaricar: ["prebarikatu", "nork"],
  preludiar: ["hasiera eman", "nor"],
  "exigir rescate": ["erreskate eskatu", "nork"],
  seguirse: ["ondorioztatu", "nor"],
  prendarse: ["maitemindu", "nor"],
  equivocarse: ["oker egon", "nor"],
  carcajearse: ["barre algaraka egin", "nork"],
  "arrogárselo": ["bereganatu", "nork"],
  "caer en la cuenta": ["konturatu", "nor"],
  confitar: ["konfitatu", "nork"],
  derrotar: ["garaitze egin", "nork"],
  circuncidar: ["zirzinzidatu", "nork"],
  acometer: ["erasotze egin", "nork"],
  equivocar: ["oker egin", "nork"],
  abominar: ["gorroto izateari ekin", "nork"],
  conjurar: ["erregutze egin", "nork"],
  menguar: ["gutxitu", "nork"],
  sujetar: ["eusteari ekin", "nork"],
  desterrar: ["erbesteratu", "nork"],
  vejar: ["jazarri", "nork"],
  retratar: ["erretratatu", "nork"],
  descarriar: ["bidegabetu", "nork"],
  exhortar: ["animatu", "nork"],
  "quebrar la solidez": ["ahultze egin", "nork"],
  "hacer perdurable": ["iraunkortu", "nork"],
  reorientar: ["birbideratu", "nork"],
  atenuar: ["leundu", "nork"],
  exacerbar: ["areagotu", "nork"],
  cuajar: ["gogortze egin", "nor"],
  "hendir el campo": ["polarizatu", "nork"],
  sortear: ["saihestu", "nork"],
  enmarcar: ["markoan jarri", "nork"],
  estigmatizar: ["estigmatizatu", "nork"],
  "restar peso": ["pisua kendu", "nork"],
  "dar cuerpo": ["sendoago egin", "nork"],
  reforzar: ["indartu", "nork"],
  "hacer temblar": ["dararazi", "nork"],
  balizar: ["seinaleztatu", "nork"],
  acondicionar: ["egokitu", "nork"],
  "tratar con tiento": ["kontuz tratatu", "nork"],
  desactivar: ["desaktibatu", "nork"],
  destronar: ["tronutik kendu", "nork"],
  "restar crédito": ["kreditua kendu", "nork"],
  deslegitimar: ["legitimitatea kendu", "nork"],
  "someter a tributo": ["zergapetu", "nork"],
  presupuestar: ["aurrekontu egin", "nork"],
  "dar primacía": ["lehentasuna eman", "nork"],
  avalar: ["bermea eman", "nork"],
  "cargar con": ["bere gain hartu", "nork"],
  "poner en guardia": ["abisu eman", "nork"],
  "poner en peligro": ["arriskuan jarri", "nork"],
  adherirse: ["atxiki", "nor"],
  "pasar a escrito": ["idatziz jarri", "nork"],
  reescribir: ["berridatzi", "nork"],
  "venir a parar": ["irtitzi", "nor"],
  saciar: ["asetze egin", "nork"],
  ahondar: ["sakondu", "nork"],
  "hacer más gravoso": ["astundu", "nork"],
  entenebrecer: ["ilundu", "nork"],
  reanudar: ["berriro hasi", "nor"],
  templar: ["neurriztartu", "nork"],
  atemperar: ["leuntze egin", "nork"],
  encauzar: ["bideratu", "nork"],
  "poner en el punto de mira": ["helburu jarri", "nork"],
  anteceder: ["aurretik joan", "nor"],
  suceder: ["gertatu", "nor"],
  interceder: ["bitartekari izan", "nor"],
  proceder: ["jardute egin", "nork"],
  agravar: ["okertu", "nork"],
  aligerar: ["arinago egin", "nork"],
  amplificar: ["handitu", "nork"],
  anclar: ["ainguratu", "nork"],
  aplacar: ["lasaitze egin", "nork"],
  aprehender: ["atxilotu", "nork"],
  desaprobar: ["gaitzetsi", "nork"],
  articular: ["artikulatu", "nork"],
  asignar: ["esleitu", "nork"],
  atestiguar: ["lekukotasuna eman", "nork"],
  autentificar: ["autentifikatu", "nork"],
  amordazar: ["isilarazi", "nork"],
  bascular: ["oreka galdu", "nor"],
  sesgar: ["alboratu", "nork"],
  bifurcar: ["bitan banatze egin", "nor"],
  acotar: ["mugatze egin", "nork"],
  trastornar: ["nahaste egin", "nork"],
  "poner brida": ["bridatu", "nork"],
  cuadrar: ["egokitze egin", "nork"],
  censurar: ["zensuratu", "nork"],
  aprisionar: ["giltzaperatu", "nork"],
  condenar: ["kondenatu", "nork"],
  afianzar: ["sendotu", "nork"],
  despedir: ["kaleratu", "nork"],
  consolidar: ["sendotze egin", "nork"],
  contrariar: ["kontrako izan", "nork"],
  contrapesar: ["oreka ekarri", "nork"],
  contrarrestar: ["aurre egin", "nork"],
  contravenir: ["aurka jo", "nork"],
  coordinar: ["koordinatu", "nork"],
  cotizar: ["kotizatu", "nork"],
  culminar: ["gailurreratu", "nor"],
  acumular: ["metatu", "nork"],
  desbordar: ["gainezka egin", "nork"],
  desembocar: ["amaiera izan", "nor"],
  desfasar: ["desfasean jarri", "nork"],
  decantar: ["erabakia hartu", "nork"],
  "desplazar el centro": ["deszentratu", "nork"],
  desencadenar: ["eragin", "nork"],
  destabicar: ["hesiak kendu", "nork"],
  desgranar: ["xehatze egin", "nork"],
  desacoplar: ["desakoplatu", "nork"],
  indemnizar: ["kalte-ordaina eman", "nork"],
  deshacer: ["desegite egin", "nork"],
  perjudicar: ["kalte egin", "nork"],
  abatirse: ["erortze egin", "nor"],
  degenerar: ["okertze egin", "nor"],
  degradar: ["degradatu", "nork"],
  "aliviar la carga": ["ardura arindu", "nork"],
  desbaratar: ["hondatu", "nork"],
  alijar: ["arinago bihurtu", "nork"],
  deliberar: ["hausnartze egin", "nork"],
  desmantelar: ["desmuntatu", "nork"],
  desenmascarar: ["agerrarazi", "nork"],
  desmembrar: ["zatikatze egin", "nork"],
  desmovilizar: ["desmobilizatu", "nork"],
  desvirtuar: ["desitxuratu", "nork"],
  enumerar: ["zerrendatu", "nork"],
  "quitar el techo": ["muga kendu", "nork"],
  depreciar: ["balioa galdu", "nork"],
  desajustar: ["desegokitu", "nork"],
  "sacar del aislamiento": ["isolamendutik atera", "nork"],
  desequilibrar: ["desorekatu", "nork"],
  desviar: ["desbideratu", "nork"],
  desvelar: ["agerrarazte egin", "nork"],
  diluir: ["diluitu", "nork"],
  domeñar: ["menperatze egin", "nork"],
  urdir: ["antolatu", "nork"],
  escalonar: ["mailakatu", "nork"],
  eclipsar: ["iluntze egin", "nork"],
  endulzar: ["gozatu", "nork"],
  podar: ["kimatu", "nork"],
  encajar: ["egokitzeari ekin", "nork"],
  emerger: ["agerpen izan", "nor"],
  atascar: ["blokeatze egin", "nork"],
  "mudarse en": ["bihurtu", "nor"],
  traducirse: ["itzulera izan", "nor"],
  escabullirse: ["iheska joan", "nork"],
  empeñarse: ["tematu", "nor"],
  aplicarse: ["dedikatu", "nor"],
  "ingeniárselas": ["moldatu", "nor"],
  insurreccionarse: ["matxinatu", "nor"],
  indignarse: ["haserretu", "nor"],
  ofenderse: ["mindu", "nor"],
  apoderarse: ["bereganatze egin", "nork"],
  erigirse: ["bihurtze egin", "nor"],
  interponerse: ["tartean sartu", "nor"],
  atollarse: ["trabatu", "nor"],
  atrincherarse: ["gotortu", "nor"],
  porfiar: ["tematze egin", "nor"],
  subrayar: ["azpimarratu", "nork"],
  matizar: ["ñabarduratu", "nork"],
  reglamentar: ["araudi egin", "nork"],
  reivindicar: ["errebindikatu", "nork"],
  militar: ["militatu", "nork"],
  negociar: ["negoziatu", "nork"],
  deducir: ["ondorioztatze egin", "nork"],
  presumir: ["uste izan", "nork"],
  abordar: ["heldutze egin", "nork"],
  evaluar: ["ebaluatu", "nork"],
  estimar: ["baloratu", "nork"],
  apreciar: ["balorazio egin", "nork"],
  lamentar: ["deitoratze egin", "nork"],
  felicitar: ["zoriondu", "nork"],
  reprochar: ["leporatzeari ekin", "nork"],
  reclamar: ["erreklamatu", "nork"],
  imponer: ["ezarri", "nork"],
  infligir: ["ezarpen egin", "nork"],
  atribuir: ["egoztu", "nork"],
  afectar: ["eragin", "nork"],
  paliar: ["arinago egin", "nork"],
  adquirir: ["eskuratze egin", "nork"],
  asentar: ["finkatu", "nork"],
  excluir: ["kanpo utzi", "nork"],
  aparecer: ["agertu", "nor"],
  imponerse: ["nagusitu", "nor"],
  inscribirse: ["izen eman", "nork"],
  comprometerse: ["konprometitu", "nor"],
  oponerse: ["aurka egin", "nork"],
  toparse: ["topo egin", "nork"],
  prestarse: ["prest egon", "nor"],
  sumarse: ["batu", "nor"],
  situarse: ["kokapen egin", "nor"],
  desarrollarse: ["garatu", "nor"],
  producirse: ["gertaera izan", "nor"],
  huir: ["ihesteari ekin", "nork"],
  tratarse: ["izateari ekin", "nor"],
  desconfiar: ["mesfidatu", "nork"],
  sospechar: ["susmatze egin", "nork"],
  esperarse: ["espero izan", "nork"],
  postular: ["postulatu", "nork"],
  recusar: ["errefusatu", "nork"],
  transponer: ["transposatu", "nork"],
  homologar: ["homologatu", "nork"],
  "dar el visto bueno": ["onespena eman", "nork"],
  habilitar: ["gaitu", "nork"],
  trasladar: ["lekualdatu", "nork"],
  adscribir: ["atxikitze egin", "nork"],
  reubicar: ["berkokatu", "nork"],
  contratar: ["kontratatu", "nork"],
  "fichar de otra empresa": ["fitxatu", "nork"],
  percibir: ["hauteman", "nork"],
  topar: ["muga jarri", "nork"],
  tarifar: ["tarifatu", "nork"],
  facturar: ["fakturatu", "nork"],
  cobrar: ["kobratu", "nork"],
  "cargar en cuenta": ["kontuan kargatu", "nork"],
  descontar: ["deskontatu", "nork"],
  amortizar: ["amortizatu", "nork"],
  sanear: ["sanetu", "nork"],
  relanzar: ["birlanzatu", "nork"],
  revitalizar: ["biziberritu", "nork"],
  precarizar: ["prekariotatu", "nork"],
  empobrecer: ["txirotu", "nork"],
  discriminar: ["diskriminatu", "nork"],
  favorecer: ["mesede egin", "nork"],
  privilegiar: ["pribilegiatu", "nork"],
  gravar: ["zergapetu", "nork"],
  neutralizar: ["neutralizatu", "nork"],
  reencuadrar: ["birenmarkatu", "nork"],
  reequilibrar: ["berorekatu", "nork"],
  reordenar: ["berordenatu", "nork"],
  "reprogramar plazos": ["epeak berprogramatu", "nork"],
  redesplegar: ["berhedatu", "nork"],
  revocar: ["indargabetu", "nork"],
  "digitalizar escaneo": ["eskaneatu", "nork"],
};

// Validate: no empty, aux ok
for (const [k, v] of Object.entries(OVR)) {
  if (!Array.isArray(v) || v.length !== 2) throw new Error(`bad ${k}`);
  if (!["nor", "nork", "nori"].includes(v[1])) throw new Error(`aux ${k}`);
}

fs.writeFileSync("scripts/_eu-es-eu-ovr.json", JSON.stringify(OVR, null, 0));
const newCount = Object.values(OVR).filter(([eu]) => !taken.has(eu.toLowerCase())).length;
const takenCount = Object.values(OVR).filter(([eu]) => taken.has(eu.toLowerCase())).length;
console.log({ entries: Object.keys(OVR).length, newCount, takenCount });
