/**
 * Build a German gloss file from an en-chunk using a local EN→DE map + verb table.
 * Usage: npx tsx scripts/build-de-gloss-chunk.ts 00
 */
import { readFileSync, writeFileSync } from "node:fs";

const chunk = process.argv[2];
if (!chunk) {
  console.error("Usage: npx tsx scripts/build-de-gloss-chunk.ts <NN>");
  process.exit(1);
}

const input = `scripts/en-chunks/part-${chunk}.tsv`;
const output = `src/data/german/gloss-${chunk}.tsv`;

type VerbForms = { inf: string; past: string; pp: string };

/** Common verb lemmas → spoken Perfekt forms */
const VERBS: Record<string, VerbForms> = {
  be: { inf: "sein", past: "ist gewesen", pp: "gewesen" },
  have: { inf: "haben", past: "hat gehabt", pp: "gehabt" },
  do: { inf: "tun", past: "hat getan", pp: "getan" },
  say: { inf: "sagen", past: "hat gesagt", pp: "gesagt" },
  go: { inf: "gehen", past: "ist gegangen", pp: "gegangen" },
  get: { inf: "bekommen", past: "hat bekommen", pp: "bekommen" },
  make: { inf: "machen", past: "hat gemacht", pp: "gemacht" },
  know: { inf: "wissen", past: "hat gewusst", pp: "gewusst" },
  think: { inf: "denken", past: "hat gedacht", pp: "gedacht" },
  take: { inf: "nehmen", past: "hat genommen", pp: "genommen" },
  see: { inf: "sehen", past: "hat gesehen", pp: "gesehen" },
  come: { inf: "kommen", past: "ist gekommen", pp: "gekommen" },
  want: { inf: "wollen", past: "hat gewollt", pp: "gewollt" },
  look: { inf: "schauen", past: "hat geschaut", pp: "geschaut" },
  use: { inf: "benutzen", past: "hat benutzt", pp: "benutzt" },
  find: { inf: "finden", past: "hat gefunden", pp: "gefunden" },
  give: { inf: "geben", past: "hat gegeben", pp: "gegeben" },
  tell: { inf: "erzählen", past: "hat erzählt", pp: "erzählt" },
  work: { inf: "arbeiten", past: "hat gearbeitet", pp: "gearbeitet" },
  call: { inf: "anrufen", past: "hat angerufen", pp: "angerufen" },
  try: { inf: "versuchen", past: "hat versucht", pp: "versucht" },
  ask: { inf: "fragen", past: "hat gefragt", pp: "gefragt" },
  need: { inf: "brauchen", past: "hat gebraucht", pp: "gebraucht" },
  feel: { inf: "fühlen", past: "hat gefühlt", pp: "gefühlt" },
  become: { inf: "werden", past: "ist geworden", pp: "geworden" },
  leave: { inf: "verlassen", past: "hat verlassen", pp: "verlassen" },
  put: { inf: "legen", past: "hat gelegt", pp: "gelegt" },
  mean: { inf: "bedeuten", past: "hat bedeutet", pp: "bedeutet" },
  keep: { inf: "behalten", past: "hat behalten", pp: "behalten" },
  let: { inf: "lassen", past: "hat gelassen", pp: "gelassen" },
  begin: { inf: "beginnen", past: "hat begonnen", pp: "begonnen" },
  seem: { inf: "scheinen", past: "hat geschienen", pp: "geschienen" },
  help: { inf: "helfen", past: "hat geholfen", pp: "geholfen" },
  talk: { inf: "reden", past: "hat geredet", pp: "geredet" },
  turn: { inf: "drehen", past: "hat gedreht", pp: "gedreht" },
  start: { inf: "starten", past: "hat gestartet", pp: "gestartet" },
  show: { inf: "zeigen", past: "hat gezeigt", pp: "gezeigt" },
  hear: { inf: "hören", past: "hat gehört", pp: "gehört" },
  play: { inf: "spielen", past: "hat gespielt", pp: "gespielt" },
  run: { inf: "laufen", past: "ist gelaufen", pp: "gelaufen" },
  move: { inf: "bewegen", past: "hat bewegt", pp: "bewegt" },
  live: { inf: "leben", past: "hat gelebt", pp: "gelebt" },
  believe: { inf: "glauben", past: "hat geglaubt", pp: "geglaubt" },
  bring: { inf: "bringen", past: "hat gebracht", pp: "gebracht" },
  happen: { inf: "geschehen", past: "ist geschehen", pp: "geschehen" },
  write: { inf: "schreiben", past: "hat geschrieben", pp: "geschrieben" },
  sit: { inf: "sitzen", past: "hat gesessen", pp: "gesessen" },
  stand: { inf: "stehen", past: "hat gestanden", pp: "gestanden" },
  lose: { inf: "verlieren", past: "hat verloren", pp: "verloren" },
  pay: { inf: "zahlen", past: "hat gezahlt", pp: "gezahlt" },
  meet: { inf: "treffen", past: "hat getroffen", pp: "getroffen" },
  include: { inf: "einschließen", past: "hat eingeschlossen", pp: "eingeschlossen" },
  continue: { inf: "fortsetzen", past: "hat fortgesetzt", pp: "fortgesetzt" },
  set: { inf: "setzen", past: "hat gesetzt", pp: "gesetzt" },
  learn: { inf: "lernen", past: "hat gelernt", pp: "gelernt" },
  change: { inf: "ändern", past: "hat geändert", pp: "geändert" },
  lead: { inf: "führen", past: "hat geführt", pp: "geführt" },
  understand: { inf: "verstehen", past: "hat verstanden", pp: "verstanden" },
  watch: { inf: "zuschauen", past: "hat zugeschaut", pp: "zugeschaut" },
  follow: { inf: "folgen", past: "ist gefolgt", pp: "gefolgt" },
  stop: { inf: "anhalten", past: "hat angehalten", pp: "angehalten" },
  create: { inf: "erschaffen", past: "hat erschaffen", pp: "erschaffen" },
  speak: { inf: "sprechen", past: "hat gesprochen", pp: "gesprochen" },
  read: { inf: "lesen", past: "hat gelesen", pp: "gelesen" },
  allow: { inf: "erlauben", past: "hat erlaubt", pp: "erlaubt" },
  add: { inf: "hinzufügen", past: "hat hinzugefügt", pp: "hinzugefügt" },
  spend: { inf: "ausgeben", past: "hat ausgegeben", pp: "ausgegeben" },
  grow: { inf: "wachsen", past: "ist gewachsen", pp: "gewachsen" },
  open: { inf: "öffnen", past: "hat geöffnet", pp: "geöffnet" },
  walk: { inf: "gehen", past: "ist gegangen", pp: "gegangen" },
  win: { inf: "gewinnen", past: "hat gewonnen", pp: "gewonnen" },
  offer: { inf: "anbieten", past: "hat angeboten", pp: "angeboten" },
  remember: { inf: "erinnern", past: "hat erinnert", pp: "erinnert" },
  love: { inf: "lieben", past: "hat geliebt", pp: "geliebt" },
  consider: { inf: "betrachten", past: "hat betrachtet", pp: "betrachtet" },
  appear: { inf: "erscheinen", past: "ist erschienen", pp: "erschienen" },
  buy: { inf: "kaufen", past: "hat gekauft", pp: "gekauft" },
  wait: { inf: "warten", past: "hat gewartet", pp: "gewartet" },
  serve: { inf: "dienen", past: "hat gedient", pp: "gedient" },
  die: { inf: "sterben", past: "ist gestorben", pp: "gestorben" },
  send: { inf: "senden", past: "hat gesendet", pp: "gesendet" },
  expect: { inf: "erwarten", past: "hat erwartet", pp: "erwartet" },
  build: { inf: "bauen", past: "hat gebaut", pp: "gebaut" },
  stay: { inf: "bleiben", past: "ist geblieben", pp: "geblieben" },
  fall: { inf: "fallen", past: "ist gefallen", pp: "gefallen" },
  cut: { inf: "schneiden", past: "hat geschnitten", pp: "geschnitten" },
  reach: { inf: "erreichen", past: "hat erreicht", pp: "erreicht" },
  kill: { inf: "töten", past: "hat getötet", pp: "getötet" },
  remain: { inf: "bleiben", past: "ist geblieben", pp: "geblieben" },
  suggest: { inf: "vorschlagen", past: "hat vorgeschlagen", pp: "vorgeschlagen" },
  raise: { inf: "erhöhen", past: "hat erhöht", pp: "erhöht" },
  pass: { inf: "bestehen", past: "hat bestanden", pp: "bestanden" },
  sell: { inf: "verkaufen", past: "hat verkauft", pp: "verkauft" },
  require: { inf: "erfordern", past: "hat erfordert", pp: "erfordert" },
  report: { inf: "berichten", past: "hat berichtet", pp: "berichtet" },
  decide: { inf: "entscheiden", past: "hat entschieden", pp: "entschieden" },
  pull: { inf: "ziehen", past: "hat gezogen", pp: "gezogen" },
};

/** Spanish headword → German (priority over English for ambiguous cases) */
const ES_DE: Record<string, string> = {
  casa: "Haus",
  agua: "Wasser",
  tiempo: "Zeit",
  día: "Tag",
  año: "Jahr",
  gente: "Leute",
  mujer: "Frau",
  "niño/niña": "Kind",
  mundo: "Welt",
  vida: "Leben",
  mano: "Hand",
  comida: "Essen",
  dinero: "Geld",
  hogar: "Zuhause",
  escuela: "Schule",
  "amigo/amiga": "Freund",
  familia: "Familie",
  ciudad: "Stadt",
  trabajo: "Arbeit",
  habitación: "Zimmer",
  coche: "Auto",
  puerta: "Tür",
  mesa: "Tisch",
  libro: "Buch",
  teléfono: "Telefon",
  calle: "Straße",
  mañana: "Morgen",
  noche: "Nacht",
  semana: "Woche",
  mes: "Monat",
  país: "Land",
  idioma: "Sprache",
  pregunta: "Frage",
  respuesta: "Antwort",
  idea: "Idee",
  problema: "Problem",
  lugar: "Ort",
  nombre: "Name",
  persona: "Person",
  cosa: "Ding",
};

/** English headword → German */
const EN_DE: Record<string, string> = {
  house: "Haus",
  water: "Wasser",
  time: "Zeit",
  day: "Tag",
  year: "Jahr",
  people: "Leute",
  woman: "Frau",
  child: "Kind",
  world: "Welt",
  life: "Leben",
  hand: "Hand",
  food: "Essen",
  money: "Geld",
  home: "Zuhause",
  school: "Schule",
  friend: "Freund",
  family: "Familie",
  city: "Stadt",
  job: "Job",
  room: "Zimmer",
  car: "Auto",
  door: "Tür",
  table: "Tisch",
  book: "Buch",
  phone: "Telefon",
  street: "Straße",
  morning: "Morgen",
  night: "Nacht",
  week: "Woche",
  month: "Monat",
  country: "Land",
  language: "Sprache",
  question: "Frage",
  answer: "Antwort",
  idea: "Idee",
  problem: "Problem",
  place: "Ort",
  name: "Name",
  person: "Person",
  thing: "Ding",
  important: "wichtig",
  good: "gut",
  bad: "schlecht",
  new: "neu",
  old: "alt",
  happy: "glücklich",
  sad: "traurig",
  big: "groß",
  small: "klein",
  easy: "einfach",
  difficult: "schwierig",
  beautiful: "schön",
  busy: "beschäftigt",
  tired: "müde",
  hungry: "hungrig",
  full: "voll",
  empty: "leer",
  cheap: "billig",
  expensive: "teuer",
  ready: "bereit",
  young: "jung",
  strong: "stark",
  weak: "schwach",
  hot: "heiß",
  cold: "kalt",
  long: "lang",
  short: "kurz",
  true: "wahr",
  false: "falsch",
  possible: "möglich",
  necessary: "notwendig",
  alone: "allein",
  heavy: "schwer",
  light: "leicht",
  clean: "sauber",
  dirty: "schmutzig",
  fast: "schnell",
  slow: "langsam",
  quiet: "ruhig",
  loud: "laut",
  and: "und",
  but: "aber",
  or: "oder",
  because: "weil",
  so: "also",
  however: "jedoch",
  therefore: "deshalb",
  although: "obwohl",
  "For that": "deshalb",
  moreover: "außerdem",
  nevertheless: "nichtsdestotrotz",
  unless: "es sei denn",
  while: "während",
  since: "da",
  if: "wenn",
  though: "obwohl",
  meanwhile: "inzwischen",
  otherwise: "sonst",
  besides: "außerdem",
  "even though": "obwohl",
  yet: "doch",
  thus: "somit",
  instead: "stattdessen",
  whereas: "wohingegen",
  whether: "ob",
  "even if": "auch wenn",
  "so that": "damit",
  "as soon as": "sobald",
  "in order to": "um zu",
  finally: "schließlich",
  I: "ich",
  you: "du",
  he: "er",
  she: "sie",
  it: "es",
  we: "wir",
  they: "sie",
  me: "mich",
  him: "ihn",
  her: "sie",
  us: "uns",
  them: "sie",
  my: "mein",
  your: "dein",
  his: "sein",
  this: "dieser",
  that: "jener",
  who: "wer",
  what: "was",
  someone: "jemand",
  mine: "meiner",
  yours: "deiner",
  ours: "unserer",
  theirs: "ihrer",
  myself: "mich selbst",
  everyone: "jeder",
  nobody: "niemand",
  which: "welcher",
  whose: "wessen",
  anything: "irgendetwas",
  in: "in",
  on: "auf",
  at: "an",
  to: "zu",
  for: "für",
  of: "von",
  with: "mit",
  from: "von",
  by: "durch",
  about: "über",
  into: "in",
  through: "durch",
  after: "nach",
  before: "vor",
  between: "zwischen",
  under: "unter",
  over: "über",
  without: "ohne",
  during: "während",
  against: "gegen",
  among: "unter",
  until: "bis",
  toward: "zu",
  across: "über",
  around: "um",
  behind: "hinter",
  beside: "neben",
  except: "außer",
  inside: "innerhalb",
  near: "nahe",
  very: "sehr",
  always: "immer",
  never: "nie",
  often: "oft",
  sometimes: "manchmal",
  already: "bereits",
  also: "auch",
  just: "gerade",
  still: "noch",
  even: "sogar",
  really: "wirklich",
  well: "gut",
  too: "zu",
  here: "hier",
  there: "dort",
  now: "jetzt",
  then: "dann",
  today: "heute",
  quickly: "schnell",
  slowly: "langsam",
  yesterday: "gestern",
  tomorrow: "morgen",
  almost: "fast",
  enough: "genug",
  quite: "ziemlich",
  maybe: "vielleicht",
  together: "zusammen",
  again: "wieder",
  away: "weg",
  hard: "hart",
  man: "Mann",
  boy: "Junge",
  girl: "Mädchen",
  mother: "Mutter",
  father: "Vater",
  brother: "Bruder",
  sister: "Schwester",
  baby: "Baby",
  student: "Student",
  teacher: "Lehrer",
  doctor: "Arzt",
  hospital: "Krankenhaus",
  office: "Büro",
  shop: "Laden",
  market: "Markt",
  restaurant: "Restaurant",
  hotel: "Hotel",
  airport: "Flughafen",
  station: "Bahnhof",
  train: "Zug",
  bus: "Bus",
  plane: "Flugzeug",
  bike: "Fahrrad",
  boat: "Boot",
  road: "Straße",
  park: "Park",
  garden: "Garten",
  tree: "Baum",
  flower: "Blume",
  animal: "Tier",
  dog: "Hund",
  cat: "Katze",
  bird: "Vogel",
  fish: "Fisch",
  horse: "Pferd",
  sun: "Sonne",
  moon: "Mond",
  rain: "Regen",
  wind: "Wind",
  snow: "Schnee",
  fire: "Feuer",
  earth: "Erde",
  sea: "Meer",
  river: "Fluss",
  mountain: "Berg",
  forest: "Wald",
  island: "Insel",
  weather: "Wetter",
  air: "Luft",
  sky: "Himmel",
  floor: "Boden",
  wall: "Wand",
  window: "Fenster",
  kitchen: "Küche",
  bathroom: "Badezimmer",
  bed: "Bett",
  chair: "Stuhl",
  lamp: "Lampe",
  clock: "Uhr",
  picture: "Bild",
  key: "Schlüssel",
  bag: "Tasche",
  box: "Kasten",
  paper: "Papier",
  pen: "Kugelschreiber",
  letter: "Brief",
  computer: "Computer",
  internet: "Internet",
  camera: "Kamera",
  music: "Musik",
  song: "Lied",
  film: "Film",
  game: "Spiel",
  sport: "Sport",
  ball: "Ball",
  team: "Team",
  player: "Spieler",
  ticket: "Ticket",
  trip: "Reise",
  holiday: "Urlaub",
  party: "Party",
  gift: "Geschenk",
  birthday: "Geburtstag",
  health: "Gesundheit",
  body: "Körper",
  head: "Kopf",
  face: "Gesicht",
  eye: "Auge",
  ear: "Ohr",
  mouth: "Mund",
  nose: "Nase",
  hair: "Haar",
  arm: "Arm",
  leg: "Bein",
  foot: "Fuß",
  finger: "Finger",
  heart: "Herz",
  blood: "Blut",
  pain: "Schmerz",
  medicine: "Medizin",
  law: "Gesetz",
  government: "Regierung",
  police: "Polizei",
  war: "Krieg",
  peace: "Frieden",
  news: "Nachrichten",
  story: "Geschichte",
  word: "Wort",
  number: "Zahl",
  color: "Farbe",
  size: "Größe",
  price: "Preis",
  bank: "Bank",
  card: "Karte",
  company: "Firma",
  business: "Geschäft",
  product: "Produkt",
  customer: "Kunde",
  service: "Dienst",
  meeting: "Besprechung",
  plan: "Plan",
  project: "Projekt",
  result: "Ergebnis",
  reason: "Grund",
  fact: "Tatsache",
  information: "Information",
  example: "Beispiel",
  difference: "Unterschied",
  group: "Gruppe",
  member: "Mitglied",
  art: "Kunst",
  photo: "Foto",
  sound: "Ton",
  voice: "Stimme",
  dream: "Traum",
  fear: "Angst",
  science: "Wissenschaft",
  history: "Geschichte",
  class: "Klasse",
  lesson: "Stunde",
  homework: "Hausaufgabe",
  test: "Prüfung",
  university: "Universität",
  library: "Bibliothek",
  museum: "Museum",
  cinema: "Kino",
  beach: "Strand",
  village: "Dorf",
  bridge: "Brücke",
  building: "Gebäude",
  farm: "Bauernhof",
  field: "Feld",
  future: "Zukunft",
  age: "Alter",
  neighbor: "Nachbar",
  guest: "Gast",
  boss: "Chef",
  worker: "Arbeiter",
  artist: "Künstler",
  writer: "Schriftsteller",
  rich: "reich",
  poor: "arm",
  simple: "einfach",
  first: "erst",
  last: "letzt",
  same: "gleich",
  other: "ander",
  only: "einzig",
  high: "hoch",
  low: "niedrig",
  black: "schwarz",
  white: "weiß",
  red: "rot",
  green: "grün",
  blue: "blau",
  open: "offen",
  closed: "geschlossen",
  free: "frei",
  sure: "sicher",
  right: "richtig",
  wrong: "falsch",
  early: "früh",
  late: "spät",
  far: "weit",
  left: "link",
  next: "nächst",
  main: "haupt",
  real: "echt",
  clear: "klar",
  dark: "dunkel",
  bright: "hell",
  soft: "weich",
  warm: "warm",
  cool: "kühl",
  dry: "trocken",
  wet: "nass",
  safe: "sicher",
  dangerous: "gefährlich",
  kind: "freundlich",
  nice: "nett",
  friendly: "freundlich",
  polite: "höflich",
  rude: "unhöflich",
  clever: "klug",
  funny: "lustig",
  serious: "ernst",
  famous: "berühmt",
  popular: "beliebt",
  special: "besonders",
  normal: "normal",
  strange: "seltsam",
  usual: "üblich",
  useful: "nützlich",
  useless: "nutzlos",
  impossible: "unmöglich",
  available: "verfügbar",
  public: "öffentlich",
  private: "privat",
  local: "örtlich",
  national: "national",
  international: "international",
  personal: "persönlich",
  social: "sozial",
  political: "politisch",
  economic: "wirtschaftlich",
  natural: "natürlich",
  common: "üblich",
  general: "allgemein",
  certain: "bestimmt",
  whole: "ganz",
  complete: "vollständig",
  final: "endgültig",
  recent: "kürzlich",
  modern: "modern",
  ancient: "antik",
  wide: "breit",
  narrow: "eng",
  deep: "tief",
  thick: "dick",
  thin: "dünn",
  round: "rund",
  flat: "flach",
  sharp: "scharf",
  smooth: "glatt",
  rough: "rau",
  sweet: "süß",
  bitter: "bitter",
  salty: "salzig",
  fresh: "frisch",
  raw: "roh",
  healthy: "gesund",
  sick: "krank",
  dead: "tot",
  alive: "lebendig",
  asleep: "schlafend",
  awake: "wach",
  angry: "wütend",
  afraid: "ängstlich",
  surprised: "überrascht",
  bored: "gelangweilt",
  interested: "interessiert",
  excited: "aufgeregt",
  proud: "stolz",
  lonely: "einsam",
  lucky: "glücklich",
  honest: "ehrlich",
  brave: "mutig",
  careful: "vorsichtig",
  soon: "bald",
  once: "einmal",
  twice: "zweimal",
  ever: "jemals",
  ago: "vor",
  recently: "kürzlich",
  suddenly: "plötzlich",
  immediately: "sofort",
  usually: "gewöhnlich",
  normally: "normalerweise",
  generally: "allgemein",
  especially: "besonders",
  probably: "wahrscheinlich",
  perhaps: "vielleicht",
  certainly: "gewiss",
  clearly: "klar",
  simply: "einfach",
  exactly: "genau",
  completely: "vollständig",
  nearly: "fast",
  hardly: "kaum",
  rather: "eher",
  pretty: "ziemlich",
  fairly: "ziemlich",
  extremely: "äußerst",
  highly: "hoch",
  deeply: "tief",
  widely: "weit",
  badly: "schlecht",
  carefully: "sorgfältig",
  easily: "leicht",
  happily: "glücklich",
  quietly: "leise",
  loudly: "laut",
  abroad: "im Ausland",
  outside: "draußen",
  upstairs: "oben",
  downstairs: "unten",
  everywhere: "überall",
  somewhere: "irgendwo",
  nowhere: "nirgendwo",
  anyway: "jedenfalls",
  forward: "vorwärts",
  "as if": "als ob",
  "provided that": "vorausgesetzt dass",
  "as long as": "solange",
  "in case": "falls",
  despite: "trotz",
  "in spite of": "trotz",
  "due to": "aufgrund",
  "owing to": "wegen",
  "because of": "wegen",
  "as a result": "als Ergebnis",
  "for example": "zum Beispiel",
  "in fact": "tatsächlich",
  "on the other hand": "andererseits",
  "at least": "zumindest",
  above: "über",
  below: "unter",
  beneath: "unter",
  beyond: "jenseits",
  along: "entlang",
  onto: "auf",
  upon: "auf",
  within: "innerhalb",
  throughout: "durchgehend",
  off: "von",
  past: "vorbei an",
  unlike: "im Gegensatz zu",
  via: "über",
  concerning: "betreffend",
  regarding: "bezüglich",
  including: "einschließlich",
  plus: "plus",
  amid: "inmitten",
  its: "sein",
  our: "unser",
  their: "ihr",
  hers: "ihrer",
  these: "diese",
  those: "jene",
  whom: "wen",
  nothing: "nichts",
  yourself: "dich selbst",
  itself: "sich selbst",
  wife: "Ehefrau",
  husband: "Ehemann",
  son: "Sohn",
  daughter: "Tochter",
  uncle: "Onkel",
  aunt: "Tante",
  cousin: "Cousin",
  parent: "Elternteil",
  couple: "Paar",
  king: "König",
  queen: "Königin",
  soldier: "Soldat",
  nurse: "Pfleger",
  engineer: "Ingenieur",
  lawyer: "Anwalt",
  cook: "Koch",
  waiter: "Kellner",
  driver: "Fahrer",
  farmer: "Landwirt",
  scientist: "Wissenschaftler",
  journalist: "Journalist",
  actor: "Schauspieler",
  singer: "Sänger",
  manager: "Manager",
  owner: "Besitzer",
  partner: "Partner",
  stranger: "Fremder",
  audience: "Publikum",
  crowd: "Menge",
  citizen: "Bürger",
  patient: "Patient",
  tourist: "Tourist",
  passenger: "Fahrgast",
  staff: "Personal",
  town: "Kleinstadt",
  capital: "Hauptstadt",
  church: "Kirche",
  castle: "Schloss",
  factory: "Fabrik",
  supermarket: "Supermarkt",
  pharmacy: "Apotheke",
  bakery: "Bäckerei",
  cafe: "Café",
  bar: "Bar",
  stadium: "Stadion",
  theatre: "Theater",
  gym: "Fitnessstudio",
  pool: "Schwimmbad",
  lake: "See",
  ocean: "Ozean",
  desert: "Wüste",
  valley: "Tal",
  hill: "Hügel",
  coast: "Küste",
  path: "Weg",
  corner: "Ecke",
  address: "Adresse",
  area: "Gebiet",
  region: "Region",
  district: "Bezirk",
  ceiling: "Decke",
  roof: "Dach",
  stairs: "Treppe",
  garage: "Garage",
  bedroom: "Schlafzimmer",
  apartment: "Wohnung",
  hour: "Stunde",
  minute: "Minute",
  second: "Sekunde",
  afternoon: "Nachmittag",
  evening: "Abend",
  season: "Jahreszeit",
  spring: "Frühling",
  summer: "Sommer",
  autumn: "Herbst",
  winter: "Winter",
  century: "Jahrhundert",
  moment: "Moment",
  date: "Datum",
  present: "Gegenwart",
  bread: "Brot",
  milk: "Milch",
  cheese: "Käse",
  meat: "Fleisch",
  egg: "Ei",
  fruit: "Obst",
  apple: "Apfel",
  orange: "Orange",
  banana: "Banane",
  vegetable: "Gemüse",
  potato: "Kartoffel",
  tomato: "Tomate",
  rice: "Reis",
  sugar: "Zucker",
  salt: "Salz",
  oil: "Öl",
  coffee: "Kaffee",
  tea: "Tee",
  wine: "Wein",
  beer: "Bier",
  juice: "Saft",
  breakfast: "Frühstück",
  lunch: "Mittagessen",
  dinner: "Abendessen",
  meal: "Mahlzeit",
  butter: "Butter",
  soup: "Suppe",
  chicken: "Huhn",
  salad: "Salat",
  chocolate: "Schokolade",
  clothes: "Kleidung",
  shirt: "Hemd",
  dress: "Kleid",
  trousers: "Hose",
  shoes: "Schuhe",
  coat: "Mantel",
  hat: "Hut",
  bottle: "Flasche",
  cup: "Tasse",
  glass: "Glas",
  plate: "Teller",
  knife: "Messer",
  fork: "Gabel",
  spoon: "Löffel",
  fridge: "Kühlschrank",
  oven: "Ofen",
  screen: "Bildschirm",
  message: "Nachricht",
  email: "E-Mail",
  website: "Website",
  password: "Passwort",
  data: "Daten",
  file: "Datei",
  tool: "Werkzeug",
  machine: "Maschine",
  engine: "Motor",
  wheel: "Rad",
  battery: "Batterie",
  success: "Erfolg",
  failure: "Misserfolg",
  chance: "Chance",
  choice: "Wahl",
  decision: "Entscheidung",
  opinion: "Meinung",
  advice: "Rat",
  knowledge: "Wissen",
  skill: "Fähigkeit",
  experience: "Erfahrung",
  memory: "Gedächtnis",
  thought: "Gedanke",
  feeling: "Gefühl",
  hope: "Hoffnung",
  love: "Liebe",
  truth: "Wahrheit",
  mistake: "Fehler",
  accident: "Unfall",
  danger: "Gefahr",
  risk: "Risiko",
  power: "Macht",
  change: "Änderung",
  effect: "Wirkung",
  purpose: "Zweck",
  goal: "Ziel",
  value: "Wert",
  quality: "Qualität",
  amount: "Menge",
  speed: "Geschwindigkeit",
  weight: "Gewicht",
  height: "Höhe",
  distance: "Entfernung",
  direction: "Richtung",
  side: "Seite",
  beginning: "Anfang",
  end: "Ende",
  method: "Methode",
  system: "System",
  process: "Prozess",
  rule: "Regel",
  role: "Rolle",
  crime: "Verbrechen",
  tax: "Steuer",
  salary: "Gehalt",
  cost: "Kosten",
  bill: "Rechnung",
  report: "Bericht",
  list: "Liste",
  note: "Notiz",
  page: "Seite",
  title: "Titel",
  author: "Autor",
  newspaper: "Zeitung",
  magazine: "Zeitschrift",
  radio: "Radio",
  television: "Fernsehen",
  energy: "Energie",
  environment: "Umwelt",
  society: "Gesellschaft",
  culture: "Kultur",
  religion: "Religion",
  yellow: "gelb",
  brown: "braun",
  grey: "grau",
  pink: "rosa",
  purple: "lila",
  huge: "riesig",
  tiny: "winzig",
  tall: "groß",
  ugly: "hässlich",
  smart: "schlau",
  lazy: "faul",
  nervous: "nervös",
  worried: "besorgt",
  confused: "verwirrt",
  disappointed: "enttäuscht",
  jealous: "eifersüchtig",
  shy: "schüchtern",
  confident: "selbstbewusst",
  generous: "großzügig",
  selfish: "egoistisch",
  cruel: "grausam",
  gentle: "sanft",
  wild: "wild",
  crowded: "überfüllt",
  comfortable: "bequem",
  convenient: "praktisch",
  when: "wenn",
  as: "als",
  official: "offiziell",
};

function translateWord(english: string, spanish: string): string | null {
  const byEs = ES_DE[spanish];
  if (byEs) return byEs;
  const byEn = EN_DE[english] ?? EN_DE[english.toLowerCase()];
  if (byEn) return byEn;
  return null;
}

function translateVerb(englishInf: string): VerbForms | null {
  const key = englishInf.toLowerCase().replace(/^to\s+/, "");
  return VERBS[key] ?? null;
}

const lines = readFileSync(input, "utf8")
  .split("\n")
  .map((l) => l.trim())
  .filter(Boolean);

const out: string[] = [];
const missing: string[] = [];

for (const line of lines) {
  const parts = line.split("\t");
  const kind = parts[0];
  const id = parts[1];
  if (kind === "V") {
    const forms = translateVerb(parts[2] ?? "");
    if (!forms) {
      missing.push(line);
      continue;
    }
    out.push(["V", id, forms.inf, forms.past, forms.pp].join("\t"));
  } else {
    const german = translateWord(parts[3] ?? "", parts[4] ?? "");
    if (!german) {
      missing.push(line);
      continue;
    }
    out.push(["W", id, german].join("\t"));
  }
}

if (missing.length > 0) {
  console.error(`Missing ${missing.length} translations for part-${chunk}`);
  console.error(missing.slice(0, 30).join("\n"));
  if (missing.length > 30) console.error(`... and ${missing.length - 30} more`);
  process.exit(1);
}

writeFileSync(output, `${out.join("\n")}\n`, "utf8");
console.log(`wrote ${output} (${out.length} lines)`);
