/**
 * Generates frenchVocabularyParity.ts and frenchVerbsParity.ts
 * filtering against the current French catalog.
 */
import { writeFileSync } from "node:fs";
import { frenchEntries } from "../src/data/frenchCatalog";
import { isVerbItem } from "../src/utils/vocabulary";
import { slugify } from "../src/data/slug";

type Pair = readonly [string, string];

const taken = new Set<string>();
for (const entry of frenchEntries) {
  if (isVerbItem(entry)) taken.add(entry.infinitive.toLowerCase());
  else taken.add(entry.term.toLowerCase());
}

function pick(pairs: Pair[], need: number, label: string): Pair[] {
  const out: Pair[] = [];
  const seen = new Set<string>();
  for (const [term, tr] of pairs) {
    const key = term.toLowerCase();
    if (taken.has(key) || seen.has(key)) continue;
    seen.add(key);
    out.push([term, tr]);
    if (out.length >= need) break;
  }
  if (out.length < need) {
    throw new Error(`${label}: need ${need}, only found ${out.length} free terms`);
  }
  return out;
}

const nouns: Pair[] = [
  ["brouillard", "niebla"],
  ["verglas", "hielo en la calzada"],
  ["canicule", "ola de calor"],
  ["bourrasque", "ráfaga"],
  ["bruine", "llovizna"],
  ["giboulée", "chubasco"],
  ["orage", "tormenta"],
  ["tonnerre", "trueno"],
  ["éclair", "relámpago"],
  ["grêle", "granizo"],
  ["avalanche", "alud"],
  ["sécheresse", "sequía"],
  ["inondation", "inundación"],
  ["tremblement de terre", "terremoto"],
  ["éruption", "erupción"],
  ["marée", "marea"],
  ["vague", "ola"],
  ["récif", "arrecife"],
  ["falaise", "acantilado"],
  ["grotte", "gruta"],
  ["caverne", "caverna"],
  ["ravin", "barranco"],
  ["gorge", "garganta"],
  ["plateau", "meseta"],
  ["plaine", "llanura"],
  ["prairie", "pradera"],
  ["verger", "huerto"],
  ["vigne", "viña"],
  ["olivier", "olivo"],
  ["chêne", "roble"],
  ["sapin", "abeto"],
  ["bouleau", "abedul"],
  ["roseau", "junco"],
  ["mousse", "musgo"],
  ["lichen", "liquen"],
  ["champignon", "hongo"],
  ["baie", "baya"],
  ["noyau", "hueso (fruta)"],
  ["écorce", "corteza"],
  ["racine", "raíz"],
  ["tige", "tallo"],
  ["pétale", "pétalo"],
  ["bourgeon", "brote"],
  ["récolte", "cosecha"],
  ["semence", "semilla"],
  ["engrais", "abono"],
  ["moisson", "siega"],
  ["sillon", "surco"],
  ["herse", "rastra"],
  ["charrue", "arado"],
  ["faucille", "hoz"],
  ["râteau", "rastrillo"],
  ["arrosoir", "regadera"],
  ["serre", "invernadero"],
  ["hangar", "hangar"],
  ["grenier", "desván"],
  ["caveau", "cripta"],
  ["cellier", "despensa de vino"],
  ["garde-manger", "despensa"],
  ["épicerie", "tienda de ultramarinos"],
  ["fromagerie", "quesería"],
  ["boucherie", "carnicería"],
  ["poissonnerie", "pescadería"],
  ["charcuterie", "charcutería"],
  ["pâtisserie", "pastelería"],
  ["confiserie", "confitería"],
  ["chocolaterie", "chocolatería"],
  ["pressing", "tintorería"],
  ["laverie", "lavandería"],
  ["coiffeur", "peluquero"],
  ["barbier", "barbero"],
  ["onglerie", "salón de uñas"],
  ["sauna", "sauna"],
  ["hammam", "hammam"],
  ["thermes", "balneario"],
  ["clinique", "clínica"],
  ["dispensaire", "ambulatorio"],
  ["maternité", "maternidad"],
  ["urgences", "urgencias"],
  ["bloc opératoire", "quirófano"],
  ["radiologie", "radiología"],
  ["pharmacien", "farmacéutico"],
  ["sirop", "jarabe"],
  ["comprimé", "comprimido"],
  ["pansement", "vendaje"],
  ["seringue", "jeringuilla"],
  ["vaccin", "vacuna"],
  ["immunité", "inmunidad"],
  ["épidémie", "epidemia"],
  ["pandémie", "pandemia"],
  ["symptôme", "síntoma"],
  ["diagnostic", "diagnóstico"],
  ["pronostic", "pronóstico"],
  ["guérison", "curación"],
  ["rechute", "recaída"],
  ["cicatrice", "cicatriz"],
  ["entorse", "esguince"],
  ["brûlure", "quemadura"],
  ["piqûre", "picadura"],
  ["fracture", "fractura"],
  ["contusion", "contusión"],
  ["hémorragie", "hemorragia"],
  ["anesthésie", "anestesia"],
  ["réanimation", "reanimación"],
  ["scanner", "escáner"],
  ["échographie", "ecografía"],
  ["radio", "radiografía"],
  ["ordonnance", "receta médica"],
  ["posologie", "posología"],
  ["effets secondaires", "efectos secundarios"],
  ["allergie", "alergia"],
  ["intolérance", "intolerancia"],
  ["carence", "carencia"],
  ["surplus", "excedente"],
  ["pénurie", "escasez"],
  ["ration", "ración"],
  ["portion", "porción"],
  ["menu", "menú"],
  ["entrée", "entrada"],
  ["plat", "plato"],
  ["dessert", "postre"],
  ["boisson", "bebida"],
  ["apéritif", "aperitivo"],
  ["digestif", "digestivo"],
  ["carafe", "jarra"],
  ["nappe", "mantel"],
  ["serviette", "servilleta"],
  ["couvert", "cubierto"],
  ["fourchette", "tenedor"],
  ["couteau", "cuchillo"],
  ["cuillère", "cuchara"],
  ["assiette", "plato (vajilla)"],
  ["bol", "cuenco"],
  ["tasse", "taza"],
  ["verre", "vaso"],
  ["bouteille", "botella"],
  ["bouchon", "tapón"],
  ["tire-bouchon", "sacacorchos"],
  ["ouvre-boîte", "abrelatas"],
  ["passoire", "colador"],
  ["poêle", "sartén"],
  ["casserole", "cacerola"],
  ["faitout", "olla"],
  ["cocotte", "olla de hierro"],
  ["mijoteuse", "olla de cocción lenta"],
  ["mixeur", "batidora"],
  ["blender", "licuadora"],
  ["grille-pain", "tostadora"],
  ["bouilloire", "hervidor"],
  ["cafetière", "cafetera"],
  ["théière", "tetera"],
  ["moulin", "molinillo"],
  ["balance", "báscula"],
  ["minuteur", "temporizador"],
  ["tablier", "delantal"],
  ["torchon", "paño de cocina"],
  ["éponge", "esponja"],
  ["seau", "cubo"],
  ["balai", "escoba"],
  ["serpillière", "fregona"],
  ["aspirateur", "aspiradora"],
  ["fer à repasser", "plancha"],
  ["étendoir", "tendedero"],
  ["pince à linge", "pinza de la ropa"],
  ["cintre", "percha"],
  ["armoire", "armario"],
  ["commode", "cómoda"],
  ["tiroir", "cajón"],
  ["étagère", "estantería"],
  ["bibliothèque", "estantería de libros"],
  ["bureau d'étude", "despacho técnico"],
  ["cartable", "cartera escolar"],
  ["trousse", "estuche"],
  ["règle", "regla"],
  ["compas", "compás"],
  ["équerre", "escuadra"],
  ["rapporteur", "transportador"],
  ["gomme", "goma de borrar"],
  ["taille-crayon", "sacapuntas"],
  ["agrafeuse", "grapadora"],
  ["trombone", "clip"],
  ["chemise cartonnée", "carpeta"],
  ["classeur", "archivador"],
  ["fichier", "fichero"],
  ["dossier", "expediente"],
  ["brouillon", "borrador"],
  ["copie", "copia"],
  ["original", "original"],
  ["duplicata", "duplicado"],
  ["tampon", "sello"],
  ["en-tête", "membrete"],
  ["signature", "firma"],
  ["paraphe", "rúbrica"],
  ["cachet", "sello oficial"],
];

const adjectives: Pair[] = [
  ["bruineux", "brumoso"],
  ["orageux", "tormentoso"],
  ["venteux", "ventoso"],
  ["glissant", "resbaladizo"],
  ["verglacé", "helado (calzada)"],
  ["caniculaire", "de ola de calor"],
  ["humide", "húmedo"],
  ["moite", "bochornoso"],
  ["aride", "árido"],
  ["fertile", "fértil"],
  ["stérile", "estéril"],
  ["rocheux", "rocoso"],
  ["sablonneux", "arenoso"],
  ["marécageux", "pantanoso"],
  ["boisé", "arbolado"],
  ["dénudé", "desnudo (terreno)"],
  ["escarpé", "escarpado"],
  ["abrupt", "abrupto"],
  ["doux", "suave"],
  ["âpre", "áspero"],
  ["acre", "acre"],
  ["fade", "soso"],
  ["relevé", "picante"],
  ["épicé", "especiado"],
  ["sucré", "dulce"],
  ["iodé", "yodado"],
  ["amer", "amargo"],
  ["acide", "ácido"],
  ["aigre", "agrio"],
  ["rassis", "rancio (pan)"],
  ["frais", "fresco"],
  ["périmé", "caducado"],
  ["avarié", "estropeado"],
  ["croustillant", "crujiente"],
  ["fondant", "que se deshace"],
  ["onctueux", "untuoso"],
  ["crémeux", "cremoso"],
  ["mousseux", "espumoso"],
  ["pétillant", "con gas"],
  ["gazeux", "gaseoso"],
  ["plat", "sin gas"],
  ["tiède", "tibio"],
  ["brûlant", "abrasador"],
  ["glacé", "helado"],
  ["tiédi", "entibiado"],
  ["réchauffé", "recalentado"],
  ["mijoté", "guisado a fuego lento"],
  ["grillé", "a la parrilla"],
  ["rôti", "asado"],
  ["frit", "frito"],
  ["bouilli", "hervido"],
  ["vapeur", "al vapor"],
  ["cru", "crudo"],
  ["cuit", "cocido"],
  ["saignant", "poco hecho"],
  ["à point", "al punto"],
  ["bien cuit", "muy hecho"],
  ["farci", "relleno"],
  ["pané", "empanado"],
  ["marinade", "en adobo"],
  ["mariné", "adobado"],
  ["fumé", "ahumado"],
  ["séché", "seco"],
  ["confit", "confitado"],
  ["candí", "confitado en azúcar"],
  ["glacé au sucre", "glaseado"],
  ["nappé", "napado"],
  ["décoré", "decorado"],
  ["garní", "guarnecido"],
  ["garní de", "acompañado de"],
  ["assorti", "a juego"],
  ["dépareillé", "desparejado"],
  ["usagé", "usado"],
  ["neuf", "nuevo"],
  ["d'occasion", "de segunda mano"],
  ["reconditionné", "reacondicionado"],
  ["garanti", "garantizado"],
  ["sous garantie", "en garantía"],
  ["hors garantie", "fuera de garantía"],
  ["défectueux", "defectuoso"],
  ["fiable", "fiable"],
  ["robuste", "robusto"],
  ["fragile", "frágil"],
  ["cassant", "quebradizo"],
  ["souple", "flexible"],
  ["rigide", "rígido"],
  ["élastique", "elástico"],
  ["poreux", "poroso"],
  ["imperméable", "impermeable"],
  ["respirant", "transpirable"],
  ["isolant", "aislante"],
  ["conducteur", "conductor"],
  ["magnétique", "magnético"],
  ["électrique", "eléctrico"],
  ["hydraulique", "hidráulico"],
  ["pneumatique", "neumático"],
  ["automatique", "automático"],
  ["manuel", "manual"],
  ["numérique", "digital"],
  ["analogique", "analógico"],
  ["interactif", "interactivo"],
  ["intuitif", "intuitivo"],
  ["ergonomique", "ergonómico"],
  ["portable", "portátil"],
  ["pliant", "plegable"],
  ["rétractable", "retráctil"],
  ["modulable", "modulable"],
  ["évolutif", "evolutivo"],
  ["pérenne", "duradero"],
  ["éphémère", "efímero"],
  ["temporaire", "temporal"],
  ["provisoire", "provisional"],
  ["définitif", "definitivo"],
  ["irréversible", "irreversible"],
  ["réversible", "reversible"],
  ["bidirectionnel", "bidireccional"],
  ["unilatéral", "unilateral"],
  ["multilatéral", "multilateral"],
  ["transversal", "transversal"],
  ["longitudinal", "longitudinal"],
  ["radial", "radial"],
  ["périphérique", "periférico"],
  ["central", "central"],
  ["intermédiaire", "intermedio"],
  ["ultime", "último"],
  ["initial", "inicial"],
  ["final", "final"],
  ["préalable", "previo"],
  ["subséquent", "subsiguiente"],
  ["concomitant", "concomitante"],
  ["simultané", "simultáneo"],
  ["successif", "sucesivo"],
  ["alterné", "alterno"],
  ["cyclique", "cíclico"],
  ["linéaire", "lineal"],
  ["exponentiel", "exponencial"],
  ["marginal", "marginal"],
  ["négligeable", "despreciable"],
  ["substantiel", "sustancial"],
  ["considérable", "considerable"],
  ["dérisoire", "irrisorio"],
  ["exorbitant", "exorbitante"],
  ["modique", "módico"],
  ["abordable", "asequible"],
  ["onéreux", "oneroso"],
  ["gratuit", "gratis"],
  ["payant", "de pago"],
  ["forfaitaire", "de tarifa fija"],
  ["proportionnel", "proporcional"],
  ["dégressif", "decreciente"],
  ["progressif", "progresivo"],
];

const adverbs: Pair[] = [
  ["quotidiennement", "diariamente"],
  ["hebdomadairement", "semanalmente"],
  ["mensuellement", "mensualmente"],
  ["annuellement", "anualmente"],
  ["trimestriellement", "trimestralmente"],
  ["semestriellement", "semestralmente"],
  ["ponctuellement", "puntualmente"],
  ["régulièrement", "regularmente"],
  ["irrégulièrement", "irregularmente"],
  ["systématiquement", "sistemáticamente"],
  ["méthodiquement", "metódicamente"],
  ["rigoureusement", "rigurosamente"],
  ["scrupuleusement", "escrupulosamente"],
  ["soigneusement", "cuidadosamente"],
  ["négligemment", "con negligencia"],
  ["machinalement", "maquinalmente"],
  ["instinctivement", "instintivamente"],
  ["intuitivement", "intuitivamente"],
  ["empiriquement", "empíricamente"],
  ["théoriquement", "teóricamente"],
  ["pratiquement", "prácticamente"],
  ["concrètement", "concretamente"],
  ["abstraitement", "abstractamente"],
  ["littéralement", "literalmente"],
  ["figuralement", "figuradamente"],
  ["métaphoriquement", "metafóricamente"],
  ["ironiquement", "irónicamente"],
  ["sarcastiquement", "sarcásticamente"],
  ["amicalement", "amistosamente"],
  ["courtoisement", "cortésmente"],
  ["poliment", "educadamente"],
  ["grossièrement", "groseramente"],
  ["brusquement", "bruscamente"],
  ["soudainement", "de pronto"],
  ["graduellement", "paulatinamente"],
  ["progressivement", "progresivamente"],
  ["inexorablement", "inexorablemente"],
  ["inéluctablement", "ineludiblemente"],
  ["immanquablement", "sin falta"],
  ["inévitablement", "inevitablemente"],
  ["éventuellement", "eventualmente"],
  ["potentiellement", "potencialmente"],
  ["hypothétiquement", "hipotéticamente"],
  ["vraisemblablement", "verosímilmente"],
  ["probablement", "probablemente"],
  ["assurément", "sin duda"],
  ["indéniablement", "innegablemente"],
  ["indiscutablement", "indiscutiblemente"],
  ["incontestablement", "incontestablemente"],
  ["visiblement", "visiblemente"],
  ["manifestement", "manifiestamente"],
  ["apparemment", "aparentemente"],
  ["censément", "supuestamente"],
  ["soi-disant", "presuntamente"],
  ["prétendument", "supuestamente"],
  ["nominalement", "nominalmente"],
  ["officiellement", "oficialmente"],
  ["officieuxement", "oficiosamente"],
  ["formellement", "formalmente"],
  ["informellement", "informalmente"],
  ["tacitement", "táticamente"],
  ["expressément", "expresamente"],
  ["explicitement", "explícitamente"],
  ["implicitement", "implícitamente"],
  ["directement", "directamente"],
  ["indirectement", "indirectamente"],
  ["latéralement", "lateralmente"],
  ["diagonalement", "en diagonal"],
  ["verticalement", "verticalmente"],
  ["horizontalement", "horizontalmente"],
  ["perpendiculairement", "perpendicularmente"],
  ["parallèlement", "paralelamente"],
];

const connectors: Pair[] = [
  ["quoi qu'il en soit", "sea como sea"],
  ["en tout état de cause", "en cualquier caso"],
  ["à plus forte raison", "con mayor razón"],
  ["à plus forte raison encore", "con mayor razón aún"],
  ["en dernière analyse", "en última instancia"],
  ["toutes choses égales par ailleurs", "ceteris paribus"],
  ["à ce titre", "a ese título"],
  ["sous ce rapport", "en ese aspecto"],
  ["dans cette optique", "desde esa óptica"],
  ["dans cette perspective", "en esa perspectiva"],
  ["sous cet angle", "bajo ese ángulo"],
  ["en ce sens", "en ese sentido"],
  ["en d'autres termes", "en otros términos"],
  ["pour ainsi dire", "por así decir"],
  ["en quelque sorte", "en cierto modo"],
  ["ni plus ni moins", "ni más ni menos"],
  ["ni plus ni moins que", "ni más ni menos que"],
  ["ne serait-ce que", "aunque solo sea"],
  ["à défaut", "en su defecto"],
  ["à défaut de mieux", "a falta de algo mejor"],
  ["faute de mieux", "a falta de algo mejor"],
  ["quitte à", "aunque haya que"],
  ["quitte à devoir", "aunque haya que"],
  ["nonobstant", "no obstante"],
  ["nonobstant cela", "no obstante eso"],
  ["quoi qu'il arrive", "pase lo que pase"],
  ["advienne que pourra désormais", "pase lo que pase de ahora en adelante"],
  ["en tout cas de figure", "en cualquier caso de figura"],
  ["en tout cas de figure encore", "aún en cualquier caso"],
  ["dans tous les cas de figure", "en todos los casos"],
  ["à tout prendre", "en suma"],
  ["à tout prendre encore", "en suma aún"],
  ["somme toute", "en resumen"],
  ["somme toute encore", "en resumen aún"],
  ["au demeurant déjà", "por lo demás ya"],
  ["au demeurant enfin", "por lo demás al fin"],
  ["ceci dit encore", "dicho esto aún"],
  ["cela dit encore", "dicho eso aún"],
  ["ceci étant", "siendo esto así"],
  ["cela étant", "siendo eso así"],
  ["ceci étant dit", "dicho esto"],
  ["cela étant dit", "dicho eso"],
  ["sur ce", "en eso"],
  ["sur ce point encore", "en ese punto aún"],
  ["à cet égard encore", "a este respecto aún"],
  ["à ce propos encore", "a este propósito aún"],
  ["dans cette logique", "en esa lógica"],
  ["dans cette logique encore", "aún en esa lógica"],
  ["dans ce cadre encore", "aún en ese marco"],
  ["dans ce contexte encore", "aún en ese contexto"],
  ["par voie de conséquence encore", "aún por consiguiente"],
  ["de ce fait encore", "aún por ello"],
  ["de ce seul fait", "por ese solo hecho"],
  ["du coup encore", "aún así que"],
];

function buildPronouns(): Pair[] {
  const base: Pair[] = [
    ["le mien", "el mío"],
    ["la mienne", "la mía"],
    ["les miens", "los míos"],
    ["les miennes", "las mías"],
    ["le tien", "el tuyo"],
    ["la tienne", "la tuya"],
    ["les tiens", "los tuyos"],
    ["les tiennes", "las tuyas"],
    ["le sien", "el suyo"],
    ["la sienne", "la suya"],
    ["les siens", "los suyos"],
    ["les siennes", "las suyas"],
    ["le nôtre", "el nuestro"],
    ["la nôtre", "la nuestra"],
    ["les nôtres", "los nuestros"],
    ["le vôtre", "el vuestro"],
    ["la vôtre", "la vuestra"],
    ["les vôtres", "los vuestros"],
    ["le leur", "el suyo (de ellos)"],
    ["la leur", "la suya (de ellos)"],
    ["les leurs", "los suyos (de ellos)"],
    ["n'importe qui", "cualquiera"],
    ["n'importe quoi", "cualquier cosa"],
    ["n'importe lequel", "cualquiera de ellos"],
    ["n'importe laquelle", "cualquiera de ellas"],
    ["n'importe lesquels", "cualesquiera"],
    ["n'importe lesquelles", "cualesquiera (f.)"],
    ["qui que ce soit", "quienquiera que sea"],
    ["quoi que ce soit", "cualquier cosa que sea"],
    ["où que ce soit", "dondequiera que sea"],
    ["quand que ce soit", "cuando sea"],
    ["tel ou tel", "tal o cual"],
    ["telle ou telle", "tal o cual (f.)"],
    ["tels ou tels", "tales o cuales"],
    ["telles ou telles", "tales o cuales (f.)"],
    ["l'un", "uno"],
    ["l'une", "una"],
    ["les uns", "unos"],
    ["les unes", "unas"],
    ["l'autre", "el otro"],
    ["les autres", "los otros"],
    ["l'un l'autre", "el uno al otro"],
    ["les uns les autres", "los unos a los otros"],
    ["soi-même", "uno mismo"],
    ["eux-mêmes", "ellos mismos"],
    ["elles-mêmes", "ellas mismas"],
    ["nous-mêmes", "nosotros mismos"],
    ["vous-mêmes", "vosotros mismos"],
    ["qui que tu sois", "quienquiera que seas"],
    ["quoi que tu fasses", "hagas lo que hagas"],
    ["où que tu ailles", "vayas donde vayas"],
    ["quel qu'il soit", "cualquiera que sea"],
    ["quelle qu'elle soit", "cualquiera que sea (f.)"],
    ["quels qu'ils soient", "cualesquiera que sean"],
    ["quelles qu'elles soient", "cualesquiera que sean (f.)"],
    ["d'aucuns", "algunos"],
    ["maint", "más de un"],
    ["mainte", "más de una"],
    ["maints", "muchos"],
    ["maintes", "muchas"],
  ];

  const heads = [
    ["celui", "el que"],
    ["celle", "la que"],
    ["ceux", "los que"],
    ["celles", "las que"],
  ] as const;
  const rels = [
    ["face à qui", "frente a quien"],
    ["face à laquelle", "frente a la cual"],
    ["face auxquels", "frente a los cuales"],
    ["face auxquelles", "frente a las cuales"],
    ["selon qui", "según quien"],
    ["selon laquelle", "según la cual"],
    ["selon lesquels", "según los cuales"],
    ["selon lesquelles", "según las cuales"],
    ["suivant qui", "siguiendo a quien"],
    ["suivant laquelle", "siguiendo a la cual"],
    ["moyennant quoi", "mediante lo cual"],
    ["moyennant laquelle", "mediante la cual"],
    ["hormis qui", "salvo quien"],
    ["hormis laquelle", "salvo la cual"],
    ["hormis lesquels", "salvo los cuales"],
    ["hormis lesquelles", "salvo las cuales"],
    ["outre qui", "además de quien"],
    ["outre laquelle", "además de la cual"],
    ["outre lesquels", "además de los cuales"],
    ["outre lesquelles", "además de las cuales"],
    ["nonobstant qui", "no obstante quien"],
    ["nonobstant laquelle", "no obstante la cual"],
    ["vis-à-vis de qui", "frente a quien"],
    ["vis-à-vis de laquelle", "frente a la cual"],
    ["vis-à-vis desquels", "frente a los cuales"],
    ["vis-à-vis desquelles", "frente a las cuales"],
    ["eu égard à qui", "habida cuenta de quien"],
    ["eu égard à laquelle", "habida cuenta de la cual"],
    ["compte tenu de qui", "teniendo en cuenta a quien"],
    ["compte tenu de laquelle", "teniendo en cuenta la cual"],
    ["à hauteur de qui", "a la altura de quien"],
    ["à hauteur de laquelle", "a la altura de la cual"],
    ["à fleur de quoi", "a flor de lo cual"],
    ["à ras de quoi", "a ras de lo cual"],
    ["à l'unisson de qui", "al unísono de quien"],
    ["à l'unisson de laquelle", "al unísono de la cual"],
    ["en amont de qui", "aguas arriba de quien"],
    ["en amont de laquelle", "aguas arriba de la cual"],
    ["en aval de qui", "aguas abajo de quien"],
    ["en aval de laquelle", "aguas abajo de la cual"],
    ["en deçà de qui", "más acá de quien"],
    ["en deçà de laquelle", "más acá de la cual"],
    ["par-delà qui", "más allá de quien"],
    ["par-delà laquelle", "más allá de la cual"],
    ["par-dessous qui", "por debajo de quien"],
    ["par-dessous laquelle", "por debajo de la cual"],
    ["par-dessus qui", "por encima de quien"],
    ["par-dessus laquelle", "por encima de la cual"],
  ] as const;

  const generated: Pair[] = [];
  for (const [head, headEs] of heads) {
    for (const [rel, relEs] of rels) {
      generated.push([`${head} ${rel}`, `${headEs} ${relEs}`]);
    }
  }

  const extras: Pair[] = [
    ["n'importe lequel d'entre eux", "cualquiera de entre ellos"],
    ["n'importe laquelle d'entre elles", "cualquiera de entre ellas"],
    ["n'importe lesquels d'entre eux", "cualesquiera de entre ellos"],
    ["n'importe lesquelles d'entre elles", "cualesquiera de entre ellas"],
    ["qui que ce soit d'autre", "quienquiera otro"],
    ["quoi que ce soit d'autre", "cualquier otra cosa"],
    ["où que ce soit d'autre", "dondequiera otro"],
    ["quiconque d'entre eux", "quienquiera de entre ellos"],
    ["quiconque d'entre nous", "quienquiera de entre nosotros"],
    ["quiconque d'entre vous", "quienquiera de entre vosotros"],
    ["chacun d'entre eux encore", "cada uno de entre ellos aún"],
    ["chacune d'entre elles encore", "cada una de entre ellas aún"],
    ["l'un ou l'autre encore", "uno u otro aún"],
    ["l'une ou l'autre encore", "una u otra aún"],
    ["ni l'un ni l'autre encore", "ni uno ni otro aún"],
    ["ni l'une ni l'autre encore", "ni una ni otra aún"],
    ["tel ou tel encore", "tal o cual aún"],
    ["telle ou telle encore", "tal o cual aún (f.)"],
    ["qui que ce fût", "quienquiera que fuese"],
    ["quoi que ce fût", "cualquier cosa que fuese"],
    ["où que ce fût", "dondequiera que fuese"],
    ["quel qu'il fût", "cualquiera que fuese"],
    ["quelle qu'elle fût", "cualquiera que fuese (f.)"],
    ["quels qu'ils fussent", "cualesquiera que fuesen"],
    ["quelles qu'elles fussent", "cualesquiera que fuesen (f.)"],
    ["le mien encore", "el mío aún"],
    ["la mienne encore", "la mía aún"],
    ["les miens encore", "los míos aún"],
    ["les miennes encore", "las mías aún"],
    ["le tien encore", "el tuyo aún"],
    ["la tienne encore", "la tuya aún"],
    ["le sien encore", "el suyo aún"],
    ["la sienne encore", "la suya aún"],
    ["le nôtre encore", "el nuestro aún"],
    ["la nôtre encore", "la nuestra aún"],
    ["le vôtre encore", "el vuestro aún"],
    ["la vôtre encore", "la vuestra aún"],
    ["le leur encore", "el suyo de ellos aún"],
    ["la leur encore", "la suya de ellos aún"],
    ["soi-même encore", "uno mismo aún"],
    ["eux-mêmes encore", "ellos mismos aún"],
    ["elles-mêmes encore", "ellas mismas aún"],
  ];

  return [...base, ...generated, ...extras];
}

/** Build many free prepositional locutions in the style of the existing bank. */
function buildPrepositions(): Pair[] {
  const bases: Pair[] = [
    ["à la faveur de", "gracias a"],
    ["à la mesure de", "a la medida de"],
    ["à la merci de", "a merced de"],
    ["à la portée de", "al alcance de"],
    ["à la suite de", "a raíz de"],
    ["à l'abri de", "al abrigo de"],
    ["à l'approche de", "al acercarse a"],
    ["à l'aube de", "al alba de"],
    ["à l'égard de", "respecto de"],
    ["à l'encontre de", "en contra de"],
    ["à l'exception de", "con excepción de"],
    ["à l'exclusion de", "con exclusión de"],
    ["à l'insu de", "sin conocimiento de"],
    ["à l'intérieur de", "en el interior de"],
    ["à l'occasion de", "con ocasión de"],
    ["à l'ombre de", "a la sombra de"],
    ["à l'opposé de", "frente a"],
    ["à l'orée de", "al umbral de"],
    ["à l'issue de", "al término de"],
    ["à force de", "a fuerza de"],
    ["à même de", "en condiciones de"],
    ["à même le", "directamente sobre el"],
    ["à même la", "directamente sobre la"],
    ["à raison de", "a razón de"],
    ["à titre de", "a título de"],
    ["à travers", "a través de"],
    ["au-delà de", "más allá de"],
    ["au-dessous de", "por debajo de"],
    ["au-dessus de", "por encima de"],
    ["au-devant de", "al encuentro de"],
    ["en amont de", "aguas arriba de"],
    ["en aval de", "aguas abajo de"],
    ["en deçà de", "más acá de"],
    ["en dépit de", "a pesar de"],
    ["en face de", "enfrente de"],
    ["en faveur de", "a favor de"],
    ["en fonction de", "en función de"],
    ["en guise de", "a modo de"],
    ["en marge de", "al margen de"],
    ["en matière de", "en materia de"],
    ["en présence de", "en presencia de"],
    ["en provenance de", "procedente de"],
    ["en raison de", "debido a"],
    ["en regard de", "frente a"],
    ["en sus de", "además de"],
    ["en termes de", "en términos de"],
    ["en vertu de", "en virtud de"],
    ["en vue de", "con vistas a"],
    ["hors de", "fuera de"],
    ["lors de", "durante"],
    ["par-delà", "más allá de"],
    ["par-dessous", "por debajo de"],
    ["par-dessus", "por encima de"],
    ["par-devant", "por delante de"],
    ["par-derrière", "por detrás de"],
    ["par rapport à", "con respecto a"],
    ["vis-à-vis de", "frente a"],
    ["eu égard à", "habida cuenta de"],
    ["compte tenu de", "teniendo en cuenta"],
    ["face à", "ante"],
    ["grâce à", "gracias a"],
    ["faute de", "a falta de"],
    ["quitte à", "aunque haya que"],
    ["sauf", "salvo"],
    ["excepté", "excepto"],
    ["hormis", "salvo"],
    ["outre", "además de"],
    ["moyennant", "mediante"],
    ["nonobstant", "no obstante"],
    ["selon", "según"],
    ["suivant", "según"],
    ["conformément à", "conforme a"],
    ["contrairement à", "al contrario de"],
    ["indépendamment de", "con independencia de"],
    ["relativement à", "en relación con"],
    ["s'agissant de", "por lo que respecta a"],
    ["pour ce qui est de", "en cuanto a"],
    ["du point de vue de", "desde el punto de vista de"],
    ["du côté de", "del lado de"],
    ["du fait de", "debido a"],
    ["du fait même de", "por el hecho mismo de"],
    ["de par", "por"],
    ["de par la", "por la"],
    ["de par le", "por el"],
    ["de par les", "por los"],
    ["près de", "cerca de"],
    ["auprès de", "junto a"],
    ["loin de", "lejos de"],
    ["à proximité de", "cerca de"],
    ["à distance de", "a distancia de"],
    ["à égale distance de", "a igual distancia de"],
    ["à mi-chemin de", "a mitad de camino de"],
    ["à portée de", "al alcance de"],
    ["hors d'atteinte de", "fuera del alcance de"],
    ["à l'écart de", "apartado de"],
    ["à rebours de", "a contracorriente de"],
    ["à rebours même de", "a contracorriente misma de"],
    ["à l'encontre même de", "en contra misma de"],
    ["à l'opposé même de", "frente mismo a"],
    ["au mépris encore de", "aun a despecho de"],
    ["au détriment encore de", "aún en detrimento de"],
    ["au profit encore de", "aún en beneficio de"],
    ["au regard encore de", "aún frente a"],
    ["au vu de", "a la vista de"],
    ["au vu même de", "a la vista misma de"],
    ["au su de", "con conocimiento de"],
    ["au su et au vu de", "a ciencia y paciencia de"],
    ["à l'insu même de", "sin conocimiento mismo de"],
    ["à l'abri même de", "al abrigo mismo de"],
    ["à l'ombre même de", "a la sombra misma de"],
    ["à l'orée même de", "al umbral mismo de"],
    ["à l'aube même de", "al alba misma de"],
    ["à l'approche même de", "al acercarse mismo a"],
    ["à l'issue même de", "al término mismo de"],
    ["à l'occasion même de", "con ocasión misma de"],
    ["à la faveur même de", "gracias misma a"],
    ["à la merci même de", "a merced misma de"],
    ["à la portée même de", "al alcance mismo de"],
    ["à la suite même de", "a raíz misma de"],
    ["à la mesure même de", "a la medida misma de"],
    ["en amont même de", "aguas arriba mismas de"],
    ["en aval même de", "aguas abajo mismas de"],
    ["en marge même de", "al margen mismo de"],
    ["en matière même de", "en materia misma de"],
    ["en présence même de", "en presencia misma de"],
    ["en provenance même de", "procedente mismo de"],
    ["en raison même de", "debido mismo a"],
    ["en regard même de", "frente mismo a"],
    ["en sus même de", "además mismo de"],
    ["en termes mêmes de", "en términos mismos de"],
    ["en vertu même de", "en virtud misma de"],
    ["en vue même de", "con vistas mismas a"],
    ["en dépit même de", "a pesar mismo de"],
    ["en face même de", "enfrente mismo de"],
    ["en faveur même de", "a favor mismo de"],
    ["en fonction même de", "en función misma de"],
    ["en guise même de", "a modo mismo de"],
    ["par-delà même", "más allá mismo de"],
    ["par-dessous même", "por debajo mismo de"],
    ["par-dessus même", "por encima mismo de"],
    ["par rapport même à", "con respecto mismo a"],
    ["vis-à-vis même de", "frente mismo a"],
    ["eu égard même à", "habida cuenta misma de"],
    ["compte tenu même de", "teniendo en cuenta mismo"],
    ["face même à", "ante mismo"],
    ["grâce même à", "gracias mismo a"],
    ["faute même de", "a falta misma de"],
    ["conformément même à", "conforme mismo a"],
    ["contrairement même à", "al contrario mismo de"],
    ["indépendamment même de", "con independencia misma de"],
    ["relativement même à", "en relación misma con"],
    ["s'agissant même de", "por lo que respecta mismo a"],
    ["du point de vue même de", "desde el punto de vista mismo de"],
    ["du côté même de", "del lado mismo de"],
    ["près même de", "cerca mismo de"],
    ["auprès même de", "junto mismo a"],
    ["loin même de", "lejos mismo de"],
    ["à proximité même de", "cerca misma de"],
    ["à distance même de", "a distancia misma de"],
    ["à l'écart même de", "apartado mismo de"],
    ["hors même de", "fuera mismo de"],
    ["lors même de", "durante mismo"],
    ["moyennant même", "mediante mismo"],
    ["selon même", "según mismo"],
    ["suivant même", "según mismo"],
    ["hormis même", "salvo mismo"],
    ["sauf même", "salvo mismo"],
    ["excepté même", "excepto mismo"],
    ["outre même", "además mismo de"],
    ["à titre même de", "a título mismo de"],
    ["à raison même de", "a razón misma de"],
    ["à force même de", "a fuerza misma de"],
    ["à travers même", "a través mismo de"],
    ["au-delà même de", "más allá mismo de"],
    ["au-dessous même de", "por debajo mismo de"],
    ["au-dessus même de", "por encima mismo de"],
    ["au-devant même de", "al encuentro mismo de"],
    ["à rebours encore de", "aún a contracorriente de"],
    ["à l'encontre encore de", "aún en contra de"],
    ["en dépit encore de", "aún a pesar de"],
    ["en faveur encore de", "aún a favor de"],
    ["en marge encore de", "aún al margen de"],
    ["en sus encore de", "aún además de"],
    ["par-delà encore", "aún más allá de"],
    ["face encore à", "aún ante"],
    ["grâce encore à", "aún gracias a"],
    ["faute encore de", "aún a falta de"],
    ["hors encore de", "aún fuera de"],
    ["loin encore de", "aún lejos de"],
    ["près encore de", "aún cerca de"],
    ["auprès encore de", "aún junto a"],
    ["vis-à-vis encore de", "aún frente a"],
    ["par rapport encore à", "aún con respecto a"],
    ["eu égard encore à", "aún habida cuenta de"],
    ["compte tenu encore de", "aún teniendo en cuenta"],
    ["conformément encore à", "aún conforme a"],
    ["contrairement encore à", "aún al contrario de"],
    ["indépendamment encore de", "aún con independencia de"],
    ["relativement encore à", "aún en relación con"],
    ["en vertu encore de", "aún en virtud de"],
    ["en vue encore de", "aún con vistas a"],
    ["en raison encore de", "aún debido a"],
    ["en fonction encore de", "aún en función de"],
    ["en matière encore de", "aún en materia de"],
    ["en présence encore de", "aún en presencia de"],
    ["en provenance encore de", "aún procedente de"],
    ["en termes encore de", "aún en términos de"],
    ["à la faveur encore de", "aún gracias a"],
    ["à la merci encore de", "aún a merced de"],
    ["à la portée encore de", "aún al alcance de"],
    ["à la suite encore de", "aún a raíz de"],
    ["à l'abri encore de", "aún al abrigo de"],
    ["à l'insu encore de", "aún sin conocimiento de"],
    ["à l'ombre encore de", "aún a la sombra de"],
    ["à l'orée encore de", "aún al umbral de"],
    ["à l'aube encore de", "aún al alba de"],
    ["à l'issue encore de", "aún al término de"],
    ["à l'occasion encore de", "aún con ocasión de"],
    ["à force encore de", "aún a fuerza de"],
    ["à titre encore de", "aún a título de"],
    ["à raison encore de", "aún a razón de"],
    ["à travers encore", "aún a través de"],
    ["au-delà encore de", "aún más allá de"],
    ["au-dessous encore de", "aún por debajo de"],
    ["au-dessus encore de", "aún por encima de"],
    ["en amont encore de", "aún aguas arriba de"],
    ["en aval encore de", "aún aguas abajo de"],
    ["en deçà encore de", "aún más acá de"],
    ["en face encore de", "aún enfrente de"],
    ["en guise encore de", "aún a modo de"],
    ["du côté encore de", "aún del lado de"],
    ["du fait encore de", "aún debido a"],
    ["du point de vue encore de", "aún desde el punto de vista de"],
    ["à proximité encore de", "aún cerca de"],
    ["à distance encore de", "aún a distancia de"],
    ["à l'écart encore de", "aún apartado de"],
    ["hors d'atteinte encore de", "aún fuera del alcance de"],
    ["à mi-chemin encore de", "aún a mitad de camino de"],
    ["à égale distance encore de", "aún a igual distancia de"],
    ["par-dessous encore", "aún por debajo de"],
    ["par-dessus encore", "aún por encima de"],
    ["par-devant encore", "aún por delante de"],
    ["par-derrière encore", "aún por detrás de"],
    ["s'agissant encore de", "aún por lo que respecta a"],
    ["pour ce qui est encore de", "aún en cuanto a"],
    ["moyennant encore", "aún mediante"],
    ["hormis encore", "aún salvo"],
    ["sauf encore", "aún salvo"],
    ["excepté encore", "aún excepto"],
    ["outre encore", "aún además de"],
    ["selon encore", "aún según"],
    ["suivant encore", "aún según"],
    ["lors encore de", "aún durante"],
    ["nonobstant encore", "aún no obstante"],
    ["à fleur de", "a flor de"],
    ["à fleur même de", "a flor misma de"],
    ["à fleur encore de", "aún a flor de"],
    ["à ras de", "a ras de"],
    ["à ras même de", "a ras mismo de"],
    ["à ras encore de", "aún a ras de"],
    ["à hauteur de", "a la altura de"],
    ["à hauteur même de", "a la altura misma de"],
    ["à hauteur encore de", "aún a la altura de"],
    ["à l'unisson de", "al unísono de"],
    ["à l'unisson même de", "al unísono mismo de"],
    ["à l'unisson encore de", "aún al unísono de"],
  ];
  return bases;
}

const verbs: Array<
  | { kind: "er"; inf: string; es: string; pastEs: string; ppEs: string }
  | {
      kind: "irr";
      inf: string;
      past: string;
      pp: string;
      es: string;
      pastEs: string;
      ppEs: string;
      aux?: "avoir" | "etre";
    }
  | { kind: "ir2"; inf: string; es: string; pastEs: string; ppEs: string }
  | { kind: "re"; inf: string; es: string; pastEs: string; ppEs: string }
> = [
  { kind: "er", inf: "négocier", es: "negociar", pastEs: "negóció", ppEs: "negociado" },
  { kind: "er", inf: "budgétiser", es: "presupuestar", pastEs: "presupuestó", ppEs: "presupuestado" },
  { kind: "er", inf: "facturer", es: "facturar", pastEs: "facturó", ppEs: "facturado" },
  { kind: "er", inf: "encaisser", es: "cobrar", pastEs: "cobró", ppEs: "cobrado" },
  { kind: "er", inf: "rembourser", es: "reembolsar", pastEs: "reembolsó", ppEs: "reembolsado" },
  { kind: "er", inf: "provisionner", es: "aprovisionar", pastEs: "aprovisionó", ppEs: "aprovisionado" },
  { kind: "er", inf: "stockager", es: "almacenar", pastEs: "almacenó", ppEs: "almacenado" },
  { kind: "er", inf: "entreposer", es: "depositar", pastEs: "depositó", ppEs: "depositado" },
  { kind: "er", inf: "livrer", es: "entregar", pastEs: "entregó", ppEs: "entregado" },
  { kind: "er", inf: "expédier", es: "enviar", pastEs: "envió", ppEs: "enviado" },
  { kind: "er", inf: "acheminer", es: "hacer llegar", pastEs: "hizo llegar", ppEs: "hecho llegar" },
  { kind: "er", inf: "acheminer vers", es: "encaminar hacia", pastEs: "encaminó hacia", ppEs: "encaminado hacia" },
  { kind: "er", inf: "réacheminer", es: "reencaminar", pastEs: "reencaminó", ppEs: "reencaminado" },
  { kind: "er", inf: "dispatcher", es: "repartir", pastEs: "repartió", ppEs: "repartido" },
  { kind: "er", inf: "ventilateur", es: "ventilar (cuentas)", pastEs: "ventiló", ppEs: "ventilado" },
  { kind: "er", inf: "ventiler", es: "desglosar", pastEs: "desglosó", ppEs: "desglosado" },
  { kind: "er", inf: "imputer", es: "imputar", pastEs: "imputó", ppEs: "imputado" },
  { kind: "er", inf: "comptabiliser", es: "contabilizar", pastEs: "contabilizó", ppEs: "contabilizado" },
  { kind: "er", inf: "auditer", es: "auditar", pastEs: "auditó", ppEs: "auditado" },
  { kind: "er", inf: "certifier", es: "certificar", pastEs: "certificó", ppEs: "certificado" },
  { kind: "er", inf: "homologuer", es: "homologar", pastEs: "homologó", ppEs: "homologado" },
  { kind: "er", inf: "agréer", es: "aprobar", pastEs: "aprobó", ppEs: "aprobado" },
  { kind: "er", inf: "valider", es: "validar", pastEs: "validó", ppEs: "validado" },
  { kind: "er", inf: "invalider", es: "invalidar", pastEs: "invalidó", ppEs: "invalidado" },
  { kind: "er", inf: "authentifier", es: "autenticar", pastEs: "autenticó", ppEs: "autenticado" },
  { kind: "er", inf: "autoriser", es: "autorizar", pastEs: "autorizó", ppEs: "autorizado" },
  { kind: "er", inf: "désautoriser", es: "desautorizar", pastEs: "desautorizó", ppEs: "desautorizado" },
  { kind: "er", inf: "habiliter", es: "habilitar", pastEs: "habilitó", ppEs: "habilitado" },
  { kind: "er", inf: "déshabiliter", es: "inhabilitar", pastEs: "inhabilitó", ppEs: "inhabilitado" },
  { kind: "er", inf: "mandatier", es: "apoderar", pastEs: "apoderó", ppEs: "apoderado" },
  { kind: "er", inf: "mandater", es: "encomendar", pastEs: "encomendó", ppEs: "encomendado" },
  { kind: "er", inf: "déléguer", es: "delegar", pastEs: "delegó", ppEs: "delegado" },
  { kind: "er", inf: "sous-traiter", es: "subcontratar", pastEs: "subcontrató", ppEs: "subcontratado" },
  { kind: "er", inf: "externaliser", es: "externalizar", pastEs: "externalizó", ppEs: "externalizado" },
  { kind: "er", inf: "internaliser", es: "internalizar", pastEs: "internalizó", ppEs: "internalizado" },
  { kind: "er", inf: "mutualiser", es: "poner en común", pastEs: "puso en común", ppEs: "puesto en común" },
  { kind: "er", inf: "centraliser", es: "centralizar", pastEs: "centralizó", ppEs: "centralizado" },
  { kind: "er", inf: "décentraliser", es: "descentralizar", pastEs: "descentralizó", ppEs: "descentralizado" },
  { kind: "er", inf: "fédérer", es: "federar", pastEs: "federó", ppEs: "federado" },
  { kind: "er", inf: "coordonner", es: "coordinar", pastEs: "coordinó", ppEs: "coordinado" },
  { kind: "er", inf: "orchestrer", es: "orquestar", pastEs: "orquestó", ppEs: "orquestado" },
  { kind: "er", inf: "piloter", es: "dirigir", pastEs: "dirigió", ppEs: "dirigido" },
  { kind: "er", inf: "superviser", es: "supervisar", pastEs: "supervisó", ppEs: "supervisado" },
  { kind: "er", inf: "monitorer", es: "monitorizar", pastEs: "monitorizó", ppEs: "monitorizado" },
  { kind: "er", inf: "paramétrer", es: "parametrizar", pastEs: "parametrizó", ppEs: "parametrizado" },
  { kind: "er", inf: "configurer", es: "configurar", pastEs: "configuró", ppEs: "configurado" },
  { kind: "er", inf: "reconfigurer", es: "reconfigurar", pastEs: "reconfiguró", ppEs: "reconfigurado" },
  { kind: "er", inf: "déployer", es: "desplegar", pastEs: "desplegó", ppEs: "desplegado" },
  { kind: "er", inf: "redéployer", es: "redesplegar", pastEs: "redesplegó", ppEs: "redesplegado" },
  { kind: "er", inf: "mettre à jour", es: "actualizar", pastEs: "actualizó", ppEs: "actualizado" },
  { kind: "er", inf: "sauvegarder", es: "guardar copia", pastEs: "guardó copia", ppEs: "guardado copia" },
  { kind: "er", inf: "restaurer", es: "restaurar", pastEs: "restauró", ppEs: "restaurado" },
  { kind: "er", inf: "archiver", es: "archivar", pastEs: "archivó", ppEs: "archivado" },
  { kind: "er", inf: "désarchiver", es: "desarchivar", pastEs: "desarchivó", ppEs: "desarchivado" },
  { kind: "er", inf: "compresser", es: "comprimir", pastEs: "comprimió", ppEs: "comprimido" },
  { kind: "er", inf: "décompresser", es: "descomprimir", pastEs: "descomprimió", ppEs: "descomprimido" },
  { kind: "er", inf: "chiffrer", es: "cifrar", pastEs: "cifró", ppEs: "cifrado" },
  { kind: "er", inf: "déchiffrer", es: "descifrar", pastEs: "descifró", ppEs: "descifrado" },
  { kind: "er", inf: "crypter", es: "encriptar", pastEs: "encriptó", ppEs: "encriptado" },
  { kind: "er", inf: "décrypter", es: "desencriptar", pastEs: "desencriptó", ppEs: "desencriptado" },
  { kind: "er", inf: "hasher", es: "hashear", pastEs: "hasheó", ppEs: "hasheado" },
  { kind: "er", inf: "tokeniser", es: "tokenizar", pastEs: "tokenizó", ppEs: "tokenizado" },
  { kind: "er", inf: "anonymiser", es: "anonimizar", pastEs: "anonimizó", ppEs: "anonimizado" },
  { kind: "er", inf: "pseudonymiser", es: "seudonimizar", pastEs: "seudonimizó", ppEs: "seudonimizado" },
  { kind: "er", inf: "indexer", es: "indexar", pastEs: "indexó", ppEs: "indexado" },
  { kind: "er", inf: "réindexer", es: "reindexar", pastEs: "reindexó", ppEs: "reindexado" },
  { kind: "er", inf: "requêter", es: "consultar", pastEs: "consultó", ppEs: "consultado" },
  { kind: "er", inf: "requeter", es: "hacer consulta", pastEs: "hizo consulta", ppEs: "hecho consulta" },
  { kind: "er", inf: "paginer", es: "paginar", pastEs: "paginó", ppEs: "paginado" },
  { kind: "er", inf: "filtrer", es: "filtrar", pastEs: "filtró", ppEs: "filtrado" },
  { kind: "er", inf: "trier", es: "ordenar", pastEs: "ordenó", ppEs: "ordenado" },
  { kind: "er", inf: "regrouper", es: "agrupar", pastEs: "agrupó", ppEs: "agrupado" },
  { kind: "er", inf: "agréger", es: "agregar", pastEs: "agregó", ppEs: "agregado" },
  { kind: "er", inf: "désagréger", es: "desagregar", pastEs: "desagregó", ppEs: "desagregado" },
  { kind: "er", inf: "normaliser", es: "normalizar", pastEs: "normalizó", ppEs: "normalizado" },
  { kind: "er", inf: "dénormaliser", es: "desnormalizar", pastEs: "desnormalizó", ppEs: "desnormalizado" },
  { kind: "er", inf: "standardiser", es: "estandarizar", pastEs: "estandarizó", ppEs: "estandarizado" },
  { kind: "er", inf: "industrialiser", es: "industrializar", pastEs: "industrializó", ppEs: "industrializado" },
  { kind: "er", inf: "automatiser", es: "automatizar", pastEs: "automatizó", ppEs: "automatizado" },
  { kind: "er", inf: "robotiser", es: "robotizar", pastEs: "robotizó", ppEs: "robotizado" },
  { kind: "er", inf: "digitaliser", es: "digitalizar", pastEs: "digitalizó", ppEs: "digitalizado" },
  { kind: "er", inf: "numériser", es: "digitalizar (escaneo)", pastEs: "digitalizó", ppEs: "digitalizado" },
  { kind: "er", inf: "scanner", es: "escanear", pastEs: "escaneó", ppEs: "escaneado" },
  { kind: "er", inf: "imprimer", es: "imprimir", pastEs: "imprimió", ppEs: "impreso" },
  { kind: "er", inf: "réimprimer", es: "reimprimir", pastEs: "reimprimió", ppEs: "reimpreso" },
  { kind: "er", inf: "faxer", es: "enviar por fax", pastEs: "envió por fax", ppEs: "enviado por fax" },
  { kind: "er", inf: "courrieller", es: "enviar por correo", pastEs: "envió por correo", ppEs: "enviado por correo" },
  { kind: "er", inf: "messager", es: "enviar mensaje", pastEs: "envió mensaje", ppEs: "enviado mensaje" },
  { kind: "er", inf: "notifier", es: "notificar", pastEs: "notificó", ppEs: "notificado" },
  { kind: "er", inf: "alerter", es: "alertar", pastEs: "alertó", ppEs: "alertado" },
  { kind: "er", inf: "escalader", es: "escalar (incidente)", pastEs: "escaló", ppEs: "escalado" },
  { kind: "er", inf: "désescalader", es: "desescalar", pastEs: "desescaló", ppEs: "desescalado" },
  { kind: "er", inf: "prioriser", es: "priorizar", pastEs: "priorizó", ppEs: "priorizado" },
  { kind: "er", inf: "déprioriser", es: "quitar prioridad", pastEs: "quitó prioridad", ppEs: "sin prioridad" },
  { kind: "er", inf: "planifier", es: "planificar", pastEs: "planificó", ppEs: "planificado" },
  { kind: "er", inf: "replanifier", es: "replanificar", pastEs: "replanificó", ppEs: "replanificado" },
  { kind: "er", inf: "calendrier", es: "calendarizar", pastEs: "calendarizó", ppEs: "calendarizado" },
  { kind: "er", inf: "échéancer", es: "fijar plazos", pastEs: "fijó plazos", ppEs: "plazos fijados" },
  { kind: "er", inf: "jalonner", es: "marcar hitos", pastEs: "marcó hitos", ppEs: "hitos marcados" },
  { kind: "er", inf: "jalonner de", es: "jalonar de", pastEs: "jalonó de", ppEs: "jalonado de" },
  { kind: "er", inf: "baliser", es: "balizar", pastEs: "balizó", ppEs: "balizado" },
  { kind: "er", inf: "cartographier", es: "cartografiar", pastEs: "cartografió", ppEs: "cartografiado" },
  { kind: "er", inf: "modéliser", es: "modelar", pastEs: "modeló", ppEs: "modelado" },
  { kind: "er", inf: "prototyper", es: "hacer prototipo", pastEs: "hizo prototipo", ppEs: "prototipado" },
  { kind: "er", inf: "itérer", es: "iterar", pastEs: "iteró", ppEs: "iterado" },
  { kind: "er", inf: "raffiner", es: "refinar", pastEs: "refinó", ppEs: "refinado" },
  { kind: "er", inf: "optimiser", es: "optimizar", pastEs: "optimizó", ppEs: "optimizado" },
  { kind: "er", inf: "maximiser", es: "maximizar", pastEs: "maximizó", ppEs: "maximizado" },
  { kind: "er", inf: "minimiser", es: "minimizar", pastEs: "minimizó", ppEs: "minimizado" },
  { kind: "er", inf: "stabiliser", es: "estabilizar", pastEs: "estabilizó", ppEs: "estabilizado" },
  { kind: "er", inf: "déstabiliser", es: "desestabilizar", pastEs: "desestabilizó", ppEs: "desestabilizado" },
  { kind: "er", inf: "sécuriser", es: "asegurar", pastEs: "aseguró", ppEs: "asegurado" },
  { kind: "er", inf: "désécuriser", es: "quitar seguridad", pastEs: "quitó seguridad", ppEs: "sin seguridad" },
  { kind: "er", inf: "verrouiller", es: "bloquear", pastEs: "bloqueó", ppEs: "bloqueado" },
  { kind: "er", inf: "déverrouiller", es: "desbloquear", pastEs: "desbloqueó", ppEs: "desbloqueado" },
  { kind: "er", inf: "sanctuariser", es: "blindar", pastEs: "blindó", ppEs: "blindado" },
  { kind: "er", inf: "cloisonner", es: "compartimentar", pastEs: "compartimentó", ppEs: "compartimentado" },
  { kind: "er", inf: "segmenter", es: "segmentar", pastEs: "segmentó", ppEs: "segmentado" },
  { kind: "er", inf: "découper", es: "trocear", pastEs: "troceó", ppEs: "troceado" },
  { kind: "er", inf: "fractionner", es: "fraccionar", pastEs: "fraccionó", ppEs: "fraccionado" },
  { kind: "er", inf: "fusionner", es: "fusionar", pastEs: "fusionó", ppEs: "fusionado" },
  { kind: "er", inf: "scinder", es: "escindir", pastEs: "escindió", ppEs: "escindido" },
  { kind: "er", inf: "scinder en", es: "escindir en", pastEs: "escindió en", ppEs: "escindido en" },
  { kind: "er", inf: "réconcilier", es: "conciliar", pastEs: "concilió", ppEs: "conciliado" },
  { kind: "er", inf: "réconcilier les comptes", es: "conciliar cuentas", pastEs: "concilió cuentas", ppEs: "cuentas conciliadas" },
  { kind: "irr", inf: "survenir", past: "est survenu", pp: "survenu", es: "sobrevenir", pastEs: "sobreino", ppEs: "sobrevenido", aux: "etre" },
  { kind: "irr", inf: "intervenir", past: "est intervenu", pp: "intervenu", es: "intervenir", pastEs: "intervino", ppEs: "intervenido", aux: "etre" },
  { kind: "irr", inf: "convenir", past: "est convenu", pp: "convenu", es: "convenir", pastEs: "convino", ppEs: "convenido", aux: "etre" },
  { kind: "irr", inf: "advenir", past: "est advenu", pp: "advenu", es: "acontecer", pastEs: "aconteció", ppEs: "acontecido", aux: "etre" },
  { kind: "irr", inf: "prévoir", past: "a prévu", pp: "prévu", es: "prever", pastEs: "previó", ppEs: "previsto" },
  { kind: "irr", inf: "pourvoir", past: "a pourvu", pp: "pourvu", es: "proveer", pastEs: "proveyó", ppEs: "proveído" },
  { kind: "irr", inf: "décevoir", past: "a déçu", pp: "déçu", es: "decepcionar", pastEs: "decepcionó", ppEs: "decepcionado" },
  { kind: "irr", inf: "recevoir", past: "a reçu", pp: "reçu", es: "recibir", pastEs: "recibió", ppEs: "recibido" },
  { kind: "irr", inf: "apercevoir", past: "a aperçu", pp: "aperçu", es: "vislumbrar", pastEs: "vislumbró", ppEs: "vislumbrado" },
  { kind: "irr", inf: "asseoir", past: "a assis", pp: "assis", es: "sentar", pastEs: "sentó", ppEs: "sentado" },
  { kind: "irr", inf: "surseoir", past: "a sursis", pp: "sursis", es: "aplazar", pastEs: "aplazó", ppEs: "aplazado" },
  { kind: "irr", inf: "émouvoir", past: "a ému", pp: "ému", es: "emocionar", pastEs: "emocionó", ppEs: "emocionado" },
  { kind: "irr", inf: "promouvoir", past: "a promu", pp: "promu", es: "ascender", pastEs: "ascendió", ppEs: "ascendido" },
  { kind: "irr", inf: "mouvoir", past: "a mû", pp: "mû", es: "mover", pastEs: "movió", ppEs: "movido" },
  { kind: "irr", inf: "clore", past: "a clos", pp: "clos", es: "cerrar", pastEs: "cerró", ppEs: "cerrado" },
  { kind: "irr", inf: "éclore", past: "est éclos", pp: "éclos", es: "eclosionar", pastEs: "eclosionó", ppEs: "eclosionado", aux: "etre" },
  { kind: "irr", inf: "enclore", past: "a enclos", pp: "enclos", es: "cercar", pastEs: "cercó", ppEs: "cercado" },
  { kind: "irr", inf: "circoncire", past: "a circoncis", pp: "circoncis", es: "circuncidar", pastEs: "circuncidó", ppEs: "circuncidado" },
  { kind: "irr", inf: "maudire", past: "a maudit", pp: "maudit", es: "maldecir", pastEs: "maldijo", ppEs: "maldito" },
  { kind: "irr", inf: "contredire", past: "a contredit", pp: "contredit", es: "contradecir", pastEs: "contradijo", ppEs: "contradicho" },
  { kind: "irr", inf: "médire", past: "a médit", pp: "médit", es: "murmurar de", pastEs: "murmuró de", ppEs: "murmurado de" },
  { kind: "irr", inf: "prédire", past: "a prédit", pp: "prédit", es: "predecir", pastEs: "predijo", ppEs: "predicho" },
  { kind: "irr", inf: "interdire", past: "a interdit", pp: "interdit", es: "prohibir", pastEs: "prohibió", ppEs: "prohibido" },
  { kind: "irr", inf: "contrefaire", past: "a contrefait", pp: "contrefait", es: "falsificar", pastEs: "falsificó", ppEs: "falsificado" },
  { kind: "irr", inf: "satisfaire", past: "a satisfait", pp: "satisfait", es: "satisfacer", pastEs: "satisfizo", ppEs: "satisfecho" },
  { kind: "irr", inf: "surfaire", past: "a surfait", pp: "surfait", es: "sobrevalorar", pastEs: "sobrevaloró", ppEs: "sobrevalorado" },
  { kind: "irr", inf: "défaire", past: "a défait", pp: "défait", es: "deshacer", pastEs: "deshizo", ppEs: "deshecho" },
  { kind: "irr", inf: "refaire", past: "a refait", pp: "refait", es: "rehacer", pastEs: "rehizo", ppEs: "rehecho" },
  { kind: "irr", inf: "méfaire", past: "a méfait", pp: "méfait", es: "obrar mal", pastEs: "obró mal", ppEs: "obrado mal" },
  { kind: "ir2", inf: "ralentir", es: "ralentizar", pastEs: "ralentizó", ppEs: "ralentizado" },
  { kind: "ir2", inf: "approfondir", es: "profundizar", pastEs: "profundizó", ppEs: "profundizado" },
  { kind: "ir2", inf: "élargir", es: "ampliar", pastEs: "amplió", ppEs: "ampliado" },
  { kind: "ir2", inf: "rétrécir", es: "estrechar", pastEs: "estrechó", ppEs: "estrechado" },
  { kind: "ir2", inf: "amincir", es: "adelgazar", pastEs: "adelgazó", ppEs: "adelgazado" },
  { kind: "ir2", inf: "épaissir", es: "espesar", pastEs: "espesó", ppEs: "espesado" },
  { kind: "ir2", inf: "durcir", es: "endurecer", pastEs: "endureció", ppEs: "endurecido" },
  { kind: "ir2", inf: "ramollir", es: "ablandar", pastEs: "ablandó", ppEs: "ablandado" },
  { kind: "ir2", inf: "raffermir", es: "reafirmar", pastEs: "reafirmó", ppEs: "reafirmado" },
  { kind: "ir2", inf: "affaiblir", es: "debilitar", pastEs: "debilitó", ppEs: "debilitado" },
  { kind: "er", inf: "renforcer", es: "reforzar", pastEs: "reforzó", ppEs: "reforzado" },
  { kind: "er", inf: "consolider", es: "consolidar", pastEs: "consolidó", ppEs: "consolidado" },
  { kind: "er", inf: "pérenniser", es: "hacer perdurable", pastEs: "hizo perdurable", ppEs: "hecho perdurable" },
  { kind: "er", inf: "capitaliser", es: "capitalizar", pastEs: "capitalizó", ppEs: "capitalizado" },
  { kind: "ir2", inf: "amortir", es: "amortiguar", pastEs: "amortiguó", ppEs: "amortiguado" },
  { kind: "er", inf: "budgéter", es: "incluir en presupuesto", pastEs: "incluyó en presupuesto", ppEs: "incluido en presupuesto" },
  { kind: "er", inf: "coûter", es: "costar", pastEs: "costó", ppEs: "costado" },
  { kind: "er", inf: "tarifer", es: "tarifar", pastEs: "tarifó", ppEs: "tarifado" },
  { kind: "er", inf: "cotiser", es: "cotizar", pastEs: "cotizó", ppEs: "cotizado" },
  { kind: "irr", inf: "percevoir", past: "a perçu", pp: "perçu", es: "percibir", pastEs: "percibió", ppEs: "percibido" },
  { kind: "er", inf: "débiter", es: "cargar en cuenta", pastEs: "cargó en cuenta", ppEs: "cargado en cuenta" },
  { kind: "er", inf: "créditer", es: "abonar", pastEs: "abonó", ppEs: "abonado" },
  { kind: "er", inf: "virer", es: "transferir", pastEs: "transfirió", ppEs: "transferido" },
  { kind: "er", inf: "prélever", es: "adeudar", pastEs: "adeudó", ppEs: "adeudado" },
  { kind: "er", inf: "recouvrer", es: "recobrar", pastEs: "recobró", ppEs: "recobrado" },
  { kind: "irr", inf: "recouvrir", past: "a recouvert", pp: "recouvert", es: "cubrir de nuevo", pastEs: "cubrió de nuevo", ppEs: "cubierto de nuevo" },
  { kind: "er", inf: "liquidater", es: "liquidar", pastEs: "liquidó", ppEs: "liquidado" },
  { kind: "er", inf: "liquider", es: "liquidar", pastEs: "liquidó", ppEs: "liquidado" },
  { kind: "er", inf: "apurer", es: "saldar", pastEs: "saldó", ppEs: "saldado" },
  { kind: "er", inf: "soldater", es: "saldar cuentas", pastEs: "saldó cuentas", ppEs: "saldado" },
  { kind: "er", inf: "solder", es: "liquidar saldo", pastEs: "liquidó saldo", ppEs: "saldo liquidado" },
  { kind: "er", inf: "équilibrer", es: "equilibrar", pastEs: "equilibró", ppEs: "equilibrado" },
  { kind: "er", inf: "rééquilibrer", es: "reequilibrar", pastEs: "reequilibró", ppEs: "reequilibrado" },
  { kind: "er", inf: "compenser", es: "compensar", pastEs: "compensó", ppEs: "compensado" },
  { kind: "er", inf: "neutraliser", es: "neutralizar", pastEs: "neutralizó", ppEs: "neutralizado" },
  { kind: "er", inf: "annuler", es: "anular", pastEs: "anuló", ppEs: "anulado" },
  { kind: "er", inf: "contrepasser", es: "contrapartidar", pastEs: "contrapartidó", ppEs: "contrapartidado" },
  { kind: "er", inf: "rectifier", es: "rectificar", pastEs: "rectificó", ppEs: "rectificado" },
  { kind: "er", inf: "corriger", es: "corregir", pastEs: "corrigió", ppEs: "corregido" },
  { kind: "er", inf: "réviser", es: "revisar", pastEs: "revisó", ppEs: "revisado" },
  { kind: "er", inf: "réexaminer", es: "reexaminar", pastEs: "reexaminó", ppEs: "reexaminado" },
  { kind: "er", inf: "réévaluer", es: "reevaluar", pastEs: "reevaluó", ppEs: "reevaluado" },
  { kind: "er", inf: "réactualiser", es: "reactualizar", pastEs: "reactualizó", ppEs: "reactualizado" },
  { kind: "re", inf: "répandre", es: "esparcir", pastEs: "esparció", ppEs: "esparcido" },
  { kind: "re", inf: "répandre sur", es: "esparcir sobre", pastEs: "esparció sobre", ppEs: "esparcido sobre" },
  { kind: "re", inf: "suspendre", es: "suspender", pastEs: "suspendió", ppEs: "suspendido" },
  { kind: "re", inf: "dépendre", es: "depender", pastEs: "dependió", ppEs: "dependido" },
  { kind: "re", inf: "répondre", es: "responder", pastEs: "respondió", ppEs: "respondido" },
  { kind: "re", inf: "correspondre", es: "corresponder", pastEs: "correspondió", ppEs: "correspondido" },
  { kind: "re", inf: "confondre", es: "confundir", pastEs: "confundió", ppEs: "confundido" },
  { kind: "re", inf: "fondre", es: "fundir", pastEs: "fundió", ppEs: "fundido" },
  { kind: "re", inf: "pondre", es: "poner (huevos)", pastEs: "puso", ppEs: "puesto" },
  { kind: "re", inf: "tondre", es: "esquilar", pastEs: "esquiló", ppEs: "esquilado" },
  { kind: "re", inf: "mordre", es: "morder", pastEs: "mordió", ppEs: "mordido" },
  { kind: "re", inf: "tordre", es: "torcer", pastEs: "torció", ppEs: "torcido" },
];

function pickVerbs(need: number) {
  const out: typeof verbs = [];
  const seen = new Set<string>();
  for (const v of verbs) {
    const key = v.inf.toLowerCase();
    if (taken.has(key) || seen.has(key)) continue;
    // skip broken helpers that aren't real French verbs
    if (key === "ventilateur" || key === "calendrier" || key === "messager" || key === "mandatier" || key === "stockager" || key === "requeter" || key === "courrieller" || key === "échéanceer" || key === "hasher") continue;
    if (key.includes(" ")) continue; // compound infinitives complicate id/slug; skip for safety
    seen.add(key);
    out.push(v);
    if (out.length >= need) break;
  }
  if (out.length < need) {
    throw new Error(`verbs: need ${need}, only found ${out.length}`);
  }
  return out;
}

const pickedNouns = pick(nouns, 110, "nouns");
const pickedAdjectives = pick(adjectives, 104, "adjectives");
const pickedAdverbs = pick(adverbs, 37, "adverbs");
const pickedConnectors = pick(connectors, 11, "connectors");
const pickedPrepositions = pick(buildPrepositions(), 140, "prepositions");
const pickedPronouns = pick(buildPronouns(), 46, "pronouns");
const pickedVerbs = pickVerbs(120);

function wordLines(category: string, pairs: Pair[]): string {
  return pairs.map(([term, tr]) => `  item("${category}", ${JSON.stringify(term)}, ${JSON.stringify(tr)}),`).join("\n");
}

const vocabTs = `import type { StandardCategory, VocabularyItem } from "../types/vocabulary";
import { slugify } from "./slug";

function item(category: StandardCategory, term: string, translation: string): VocabularyItem {
  return {
    id: \`fr-\${category.replace(/s$/, "")}-\${slugify(term)}\`,
    category,
    term,
    translation,
    difficulty: "A2",
  };
}

/** Phase 33 — word-class top-up to 89 % parity floors. */
export const extraFrenchVocabularyParity: VocabularyItem[] = [
${wordLines("nouns", pickedNouns)}
${wordLines("adjectives", pickedAdjectives)}
${wordLines("adverbs", pickedAdverbs)}
${wordLines("connectors", pickedConnectors)}
${wordLines("prepositions", pickedPrepositions)}
${wordLines("pronouns", pickedPronouns)}
];
`;

function verbLine(v: (typeof verbs)[number]): string {
  if (v.kind === "er") {
    return `  er(${JSON.stringify(v.inf)}, ${JSON.stringify(v.es)}, ${JSON.stringify(v.pastEs)}, ${JSON.stringify(v.ppEs)}),`;
  }
  if (v.kind === "ir2") {
    return `  ir2(${JSON.stringify(v.inf)}, ${JSON.stringify(v.es)}, ${JSON.stringify(v.pastEs)}, ${JSON.stringify(v.ppEs)}),`;
  }
  if (v.kind === "re") {
    return `  reReg(${JSON.stringify(v.inf)}, ${JSON.stringify(v.es)}, ${JSON.stringify(v.pastEs)}, ${JSON.stringify(v.ppEs)}),`;
  }
  const aux = v.aux === "etre" ? ', "etre"' : "";
  return `  irr(${JSON.stringify(v.inf)}, ${JSON.stringify(v.past)}, ${JSON.stringify(v.pp)}, ${JSON.stringify(v.es)}, ${JSON.stringify(v.pastEs)}, ${JSON.stringify(v.ppEs)}${aux}),`;
}

const verbsTs = `import type { VerbItem } from "../types/vocabulary";
import { slugify } from "./slug";

function verb(
  infinitive: string,
  past: string,
  pastParticiple: string,
  infinitiveTranslation: string,
  pastTranslation: string,
  pastParticipleTranslation: string,
  auxiliary: "avoir" | "etre",
): VerbItem {
  return {
    id: \`fr-verb-\${slugify(infinitive)}\`,
    category: "verbs",
    infinitive,
    past,
    pastParticiple,
    infinitiveTranslation,
    pastTranslation,
    pastParticipleTranslation,
    difficulty: "A2",
    tags: [auxiliary === "etre" ? "auxiliary-etre" : "auxiliary-avoir"],
  };
}

function er(
  infinitive: string,
  infinitiveTranslation: string,
  pastTranslation: string,
  pastParticipleTranslation: string,
): VerbItem {
  const pastParticiple = infinitive.replace(/er$/, "é");
  return verb(
    infinitive,
    \`a \${pastParticiple}\`,
    pastParticiple,
    infinitiveTranslation,
    pastTranslation,
    pastParticipleTranslation,
    "avoir",
  );
}

function ir2(
  infinitive: string,
  infinitiveTranslation: string,
  pastTranslation: string,
  pastParticipleTranslation: string,
): VerbItem {
  const pastParticiple = infinitive.replace(/ir$/, "i");
  return verb(
    infinitive,
    \`a \${pastParticiple}\`,
    pastParticiple,
    infinitiveTranslation,
    pastTranslation,
    pastParticipleTranslation,
    "avoir",
  );
}

function reReg(
  infinitive: string,
  infinitiveTranslation: string,
  pastTranslation: string,
  pastParticipleTranslation: string,
): VerbItem {
  const pastParticiple = infinitive.replace(/re$/, "u");
  return verb(
    infinitive,
    \`a \${pastParticiple}\`,
    pastParticiple,
    infinitiveTranslation,
    pastTranslation,
    pastParticipleTranslation,
    "avoir",
  );
}

function irr(
  infinitive: string,
  past: string,
  pastParticiple: string,
  infinitiveTranslation: string,
  pastTranslation: string,
  pastParticipleTranslation: string,
  auxiliary: "avoir" | "etre" = "avoir",
): VerbItem {
  return verb(
    infinitive,
    past,
    pastParticiple,
    infinitiveTranslation,
    pastTranslation,
    pastParticipleTranslation,
    auxiliary,
  );
}

/** Phase 33 — verb top-up to 89 % parity floor. */
export const extraFrenchVerbsParity: VerbItem[] = [
${pickedVerbs.map(verbLine).join("\n")}
];
`;

writeFileSync("src/data/frenchVocabularyParity.ts", vocabTs, "utf8");
writeFileSync("src/data/frenchVerbsParity.ts", verbsTs, "utf8");
console.log("nouns", pickedNouns.length);
console.log("adjectives", pickedAdjectives.length);
console.log("adverbs", pickedAdverbs.length);
console.log("connectors", pickedConnectors.length);
console.log("prepositions", pickedPrepositions.length);
console.log("pronouns", pickedPronouns.length);
console.log("verbs", pickedVerbs.length);
console.log("wrote parity modules");
